### ISSUE TITLE
Status cover pages: "inactive" drafts

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#100]
UPDATED: 2019/04/20 Retired and Withdrawn draft covers have been updated in layout. Important dates are now displayed within the "Warning Notice" section.

This supersedes #94 .

A NIST draft can end up in one of two "inactive" states:

* Retired draft
* Withdrawn draft

A Draft can transition to these end states:
* At any stage, it can become a “Retired Draft” (attached as draft-retired-cover).
* At any stage, it can become a “Withdrawn Draft” (attached as withdrawn-draft-cover).

NOTE: These draft cover pages have a structure identical to those in #99 (i.e. ALL draft cover pages are identical in structure, barring minor additions in certain stages)

With both states,
* the cover page is PREPENDED in the document (the published cover page REMAINS).

Retired draft:

<img width="506" alt="retired-draft" src="https://user-images.githubusercontent.com/11865/56463354-64341c80-640d-11e9-8504-20133fc26846.png">

Contains these additional attributes (compared to normal Draft covers)
* Retired Date
* "Retired Document" information (information about THIS CURRENT document)
  * Status
  * Series/Number
  * Title
  * Publication Date
  * Additional Information (Can be implemented like:
```adoc
[cover-additional-information]
See https://csrc.nist.gov for information on NIST cybersecurity publications and programs.
```
)

* Compared to normal draft cover pages, there is NO Banner, NO Series Number, and NO Title/Subtitles

Withdrawn draft:

<img width="497" alt="draft-withdrawn-cover" src="https://user-images.githubusercontent.com/11865/56104017-57747c00-5f68-11e9-8f60-bef0a91ee434.png">

Contains these additional attributes (compared to normal Draft covers)
* Withdrawal Date
* "Superseding Document" information (information about THE SUPERSEDING document)
  * Status
  * Series/Number
  * Title
  * Publication Date
  * DOI
  * CSRC URL
  * Additional Information

* Compared to normal draft cover pages, there is NO Banner, NO Series Number, and NO Title/Subtitles

**Comment by opoudjis** [comment]
Cannot close this ticket until https://github.com/metanorma/metanorma-nist-style/issues/4 is done for HTML.

**Comment by ronaldtse** [comment]
New Retired Draft and Withdrawn Draft covers. These are the final ones.

Notice both of them are now in line with the rest of the Draft covers (#99).

Both have no heading title and no banners.

Retired draft:
<img width="506" alt="retired-draft" src="https://user-images.githubusercontent.com/11865/56463331-fb4ca480-640c-11e9-82c9-376d69ec6145.png">

Withdrawn draft:
<img width="511" alt="withdrawn-draft" src="https://user-images.githubusercontent.com/11865/56463332-fb4ca480-640c-11e9-8606-d1b11e04b752.png">

**Comment by opoudjis** [comment]
Retired cover page done

**Comment by opoudjis** [comment]
Is the DOI field to be populated in the retired page as well? Is the additional information in the withdrawn page to use the same content as the retired page?  Do we want the additional information boilerplate to be customizable?

**Comment by opoudjis** [comment]
Withdrawn cover page requires representation of superseding document in bibdata, and cannot assume that the information is recoverable from NistBib. Adding the following document attributes:

`:superseding-status`, `:superseding-iteration:` (if applicable), `:superseding-title:` (if applicable), 
`:superseding-circulated-date:`, `:superseding-doi:` (if applicable), `:superseding-url:`

**Comment by opoudjis** [comment]
Will need to add those doc attributes to doc template

**Comment by ronaldtse** [comment]
> Is the DOI field to be populated in the retired page as well?

I’m inclined that if there is a DOI, we can display it. That would have been displayed on the original cover anyway too. 

> Is the additional information in the withdrawn page to use the same content as the retired page?

The Retired page additional information is just a sample. There should be none by default. It should be customizable. 

> Do we want the additional information boilerplate to be customizable?

Yes. As above.

**Comment by opoudjis** [comment]
Adding "additional information" as `:bib-additional-note:`, will encode as note in bibdata of type "additional_note".

**Comment by opoudjis** [comment]
HTML done. @ronaldtse, if you have concerns about the HTML pages I've sent you, please raise a new ticket.
