### ISSUE TITLE
Status cover pages: "inactive" publications ("final" stage => "inactive")

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#101]
UPDATED 2019/04/20: Withdrawal Pending cover updated: "Publication Date" is now "Month Year", consistent with all other publication dates.

This issue supersedes #94.

A NIST publication ("final" stage) can end up in one of two "inactive" states:
* Withdrawal Pending
* Withdrawn

The only difference is:
* Withdrawal Date is in the future => "Withdrawal Pending"
* Withdrawal Date is in the past => "Withdrawn"

NOTE: The "Withdrawal Pending" cover page looks like all the other Draft cover pages in #99 and #100 . The "Withdrawn" cover page is also used by the NIST Library and therefore has a different style (font, layout, etc).

NOTE: Both states for Final are realized by a single "withdrawn" bibliographic date.

NOTE: When a "Withdrawal Pending" Final reaches the withdrawal date, replace "Withdrawal Pending" cover with "Withdrawn NIST Technical Series Publication" cover. 

With both states,

* the cover page is PREPENDED in the document (the published "final" cover page and associated attributes REMAINS). e.g.
```adoc
// Final publication withdrawn.
// Notice we need to have `stage` and `state` to keep them separate (discussion welcome)
// Or, we could infer that `withdrawn-pub` implies it has been in `final` state at some point.
:stage: final
:publication-date: 2019-02-02
:state: withdrawn
:withdrawn-date: 2019-03-02
```

* the cover pages have NO Series Number, NO Title/Subtitle, NO Banner (same as "Withdrawn Draft" in #100)

Withdrawal Pending:

<img width="509" alt="final-withdrawal-pending" src="https://user-images.githubusercontent.com/11865/56463379-0ce27c00-640e-11e9-982c-db39fb7dd980.png">

Compared to Withdrawn Draft cover, it contains only one additional attribute:

* Superseded Date

Withdrawn:

<img width="499" alt="final-withdrawn-cover" src="https://user-images.githubusercontent.com/11865/56107132-1cc61000-5f77-11e9-879e-bb8cf030abfa.png">

Compared to Withdrawn Draft cover, it contains a number of additional attributes:

* Withdrawn Document (attributes of the current document)
  * Series/Number (already exists in document)
  * Title (already exists in document)
  * Publication Date(s) (already exists in document)
  * Withdrawal Note (NEW)
* Superseding Publication(s)
  * Series/Number (exists in Withdrawal Pending cover)
  * Title (exists in Withdrawal Pending cover)
  * Publication Date (exists in Withdrawal Pending cover)
  * URL/DOI (exists in Withdrawal Pending cover)
  * Author(s) (NEW)
* Additional Information
  * Contact (NEW)
  * Latest revision of the attached publication (NEW)
  * Related information (exists in Withdrawal Pending cover)
  * Withdrawal announcement link (NEW)

**Comment by opoudjis** [comment]
Cannot close this ticket until https://github.com/metanorma/metanorma-nist-style/issues/4 is done for HTML.

**Comment by ronaldtse** [comment]
Withdrawal Pending cover updated: "Publication Date" is now "Month Year", consistent with all other publication dates.

<img width="509" alt="final-withdrawal-pending" src="https://user-images.githubusercontent.com/11865/56463387-3ac7c080-640e-11e9-8e50-3e126fc57542.png">

**Comment by opoudjis** [comment]
The date shall be indicated as `:obsoleted-date:`; that's been in place for weeks.

**Comment by opoudjis** [comment]
They are not getting slashed dates. They are getting hyphenated dates, as they do in the other samples already given.

For a standards body, NIST have been going out of their way to do things inconsistently.

**Comment by ronaldtse** [comment]
@opoudjis re: "slashed dates". 

Are you talking about this?
<img width="783" alt="Screen Shot 2019-04-23 at 11 34 45 AM" src="https://user-images.githubusercontent.com/11865/56548733-d34f7380-65bb-11e9-85f1-7f94b04956c7.png">

Or this?
<img width="563" alt="Screen Shot 2019-04-23 at 11 35 08 AM" src="https://user-images.githubusercontent.com/11865/56548740-da768180-65bb-11e9-95c3-e7d3643a18dc.png">

The former is purely a free form note.

The latter can be a concern.

**Comment by opoudjis** [comment]
The latter is a concern. Supporting both hyphens and slashes in dates is ridiculous.

**Comment by ronaldtse** [comment]
I agree. Let me ask.

**Comment by opoudjis** [comment]
One of the many grotesqueries of NIST is the accompanying of published dates by updated dates, because they don't have a proper way for versioning errata releases: https://github.com/metanorma/metanorma-nist/issues/111

One of the many inconsistencies of NIST is their cavalier formulation of updated dates: the Withdrawn page has both "November 2016 (including updates as of January 3, 2018)" and "November 2016 (updated 3/21/2018)".

They're not getting that flexibility any more. I will use the former unless told otherwise in #111.

**Comment by opoudjis** [comment]
Encoding the notes in Withdrawal page as an assortment of bibdata/notes, with a distinct type for each note: in Asciidoctor, `:bib-withdrawal-note:`, `:bib-withdrawal-announcement-link:`.

@ronaldtse What do they mean by "Latest revision of the attached publication"? A revdate? A revision number? What?

**Comment by opoudjis** [comment]
NIST have put the logo and revision date for the Withdrawn cover page in a footer.

They are not getting this either: this is nightmarish enough to maintain as is, and a conditional footer (activated only when this page is inserted) is going to be very difficult to manage in Word. I will put the logo and revision date at the bottom of the normal page.

**Comment by ronaldtse** [comment]
> NIST have put the logo and revision date for the Withdrawn cover page in a footer.

@opoudjis the "Withdrawn Publication" cover page is a NIST Library thing -- we don't have the authority to override their page. Sorry but this needs to be encoded in a separate template.

**Comment by ronaldtse** [comment]
In fact, let me confirm this. Hold on.

**Comment by ronaldtse** [comment]
OK @opoudjis I am now convinced that they look the same, keep it this way. Thanks.

**Comment by opoudjis** [comment]
HTML done. @ronaldtse, if you have concerns about the HTML pages I've sent you, please raise a new ticket.
