### ISSUE TITLE
Executive summary should be encoded as `[executive-summary]` not `[preface]`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#104]
The "Executive Summary" section is

* a special preface section: unnumbered, but starts off a new page (in Word).
* encoded in Metanorma XML as `<executivesummary>`.

Currently, to create an ES section you need to do this:

```adoc
[preface]
.Executive Summary

My executive summary...
```

But this is awkward - it is not a normal preface, and the code should *not* be encoding the XML portion by string matching the phrase "Executive Summary".

This task is to call an Executive Summary an `[executive-summary]`. This way we can do this:

```
[executive-summary]
My executive summary...
```

**Comment by opoudjis** [comment]
The executive summary shall still be a section (it is not going to be just one paragraph long), so it still requires a title:

````
[executive-summary]
= Exec Summ

Blah blah blah

blah blah blah
````
