### ISSUE TITLE
Tables/Figures in Executive Summary sections

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#105]
A Table/Figure in the Executive Summary section should be numbered "within the section" and "outside of the main document".

i.e. table/figure in Executive Summary should be labelled as "Table ES-n"/"Figure ES-n".

It might be the case that `[preface]` sections also have the same issue... if these elements are allowed?

**Comment by opoudjis** [comment]
I will not do this unless I have express confirmation from NIST. I did this once, and took it out. 

The subsections of prefaces are open-ended, and can have arbitrary titles. Using title initials for assets under the preface is a bad idea for that reason, and should be recommended against.

**Comment by ronaldtse** [comment]
> i.e. table/figure in Executive Summary should be labelled as "Table ES-n"/"Figure ES-n".

This is expressly requested by NIST, so it’s a go. Thanks!

**Comment by ronaldtse** [comment]
(Only in the Executive Summary - it is said that other Preface sections will not have figures and tables.)

**Comment by opoudjis** [comment]
Assets in appendixes are labelled as A.1, A.2, not A-1, A-2. I will code a workaround, but do consider making them ES.1, ES.2.
