### ISSUE TITLE
NIST publication bibliographic dates (CONFIRMED)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#115]
It is now agreed how we encode the date data elements of a NIST publication:

|Relaton Date | Meaning of date in Metanorma NIST Publication
|--|--
|`issued-date`| Publication Date (“Month Year”)
|`published-date`| Release Date
|`implemented-date`| NIST refers to this as an “Effective Date.” Probably not used for SP 800s, but occurs with FIPS.
|`updated-date` | Errata “update date”
|`obsoleted-date`| Withdrawal Date
|`confirmed-date`| Confirmed Date

This task is to utilize this confirmed list for Metanorma document generation.

**Comment by opoudjis** [comment]
For almost all of these, there is nothing for me to do.

I think you have the definitions of issued-date and published-date the wrong way around:

* `:issued-date:`:: The date on which the standard was issued (authorised for publication by the issuing authority).
* `:published-date:`:: The date on which the standard was published (distributed by the publisher).

I will not make any change unless I have wording from NIST, that I can copy paste into documentation, that clearly differentiates between the two dates, and explicitly says that the document is badged with the date of authorisation of release, as distinct from the date of actual release. I am sick of this constant refactoring.

And I do not trust them to maintain that distinction.

**Comment by ronaldtse** [comment]
In NIST publication terminology,

* The "NIST publication date" is the date the publication was authorized.
* The "NIST release date" is the date the publication was distributed.

It is unfortunate that their terminology is at odds with the meanings we defined, but there was careful consideration on the assignment of the date definitions. This is confirmed to be accepted by NIST.

Of course, we can propose to reverse the encoding as well, but the "meaning" in the dates will no longer be consistent (i.e. "NIST publication date" will be incomparable with "publication dates" of other documents).

* The "Month Year" is the "NIST publication date" for FINAL pubs. In DRAFT pubs, the "Month Day, Year" is the "NIST publication date"
* There is a "NIST release date" that is not being rendered in the document as of now, but needs to be in the metadata for the NIST library to (automatically) process the document.

**Comment by opoudjis** [comment]
Ugh.

**Comment by opoudjis** [comment]
In Draft pubs, the date used is the `:circulated-date:`. We should maintain that distinction.

**Comment by andrew2net** [comment]
@ronaldtse 
> * The "Month Year" is the "NIST publication date" for FINAL pubs. In DRAFT pubs, the "Month Day, Year" is the "NIST publication date"

This draft doc https://csrc.nist.gov/publications/detail/sp/500-299/draft has  "Month Year" publication date.

**Comment by ronaldtse** [comment]
@andrew2net 500-299 is an old document, and does not follow the new rules. We will have to handle these conflicts though.
