### ISSUE TITLE
Implement full/short references for "DRAFT" NIST publications (CONFIRMED)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#116]
This issue is to allow citation of Draft NIST publications.

Short: "NIST {docidentifier} ({stage-abbrev})".

e.g. "NIST SP 800-162 (3PD)"

Long: "Sriram K, Montgomery D (2018) Secure Interdomain Traffic Exchange: BGP Robustness and DDoS Mitigation. (National Institute of Standards and Technology, Gaithersburg, MD),  Draft NIST Special Publication (SP) 800-189. Available at https://csrc.nist.gov/publications/detail/sp/800-189/draft"

The relevant part is "Draft NIST Special Publication (SP) 800-189"; "Draft" is placed before "NIST Special Publication (SP)".

**Comment by opoudjis** [comment]
The citation does not mention the circulated date, which I think is a mistake; and it does not mention the stage of the draft, which is simply wrong.

**Comment by ronaldtse** [comment]
@opoudjis addressing your points:

Long: "Sriram K, Montgomery D ({Month Day, Year}) Secure Interdomain Traffic Exchange: BGP Robustness and DDoS Mitigation. (National Institute of Standards and Technology, Gaithersburg, MD), Draft ({stage-full}) NIST Special Publication (SP) 800-189. Available at https://csrc.nist.gov/publications/detail/sp/800-189/draft"

**Comment by ronaldtse** [comment]
And {stage-abbrev} = "3PD", {stage-full} = "Third Public Draft"

**Comment by opoudjis** [comment]
The identifier for a reference is either retrieved from NistBib, or it is manually inserted in the reference. 

If it is manually inserted, then the stage abbreviation will be part of what is manually inserted: someone will need to type in `NIST SP 800-189 (3PD)`. The same applies if someone types in YAML into Asciidoctor: they will still end up typing in a full short reference identifier.

If it is to be included in NistBib, that presupposes that drafts are available to be screenscraped (which I doubt); if they are available, that becomes a task for @andrew2net, to incorporate the draft abbreviation in the NistBib-generated document identifier. 

(The code to generate the abbreviation is:

````
      def iter_code(isoxml)
        docstatus = isoxml.at(ns("//bibdata/status/stage"))&.text
        return nil unless docstatus == "draft-public"
        iter = isoxml.at(ns("//bibdata/status/iteration"))&.text || "1"
        return "IPD" if iter == "1"
        return "FPD" if iter.downcase == "final"
        "#{iter}PD"
      end
````

I will generate the stage abbreviation within bibdata inside of the document.

**Comment by ronaldtse** [comment]
Only a public draft will be available via the NIST website, so the draft author must be able to specify this. 

In addition, @opoudjis EVERY stage could have iterations, just like ISO.

**Comment by opoudjis** [comment]
....

You're kidding me.

That is not what your spec said: your table only had iterations listed under public drafts.

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-model-nist/issues/16

That table is pretty clear to me.

Grrr.

**Comment by opoudjis** [comment]
And abbreviations of stages have only ever been specified for PD; I just had to make up the other abbreviations.

**Comment by ronaldtse** [comment]
@opoudjis the reason why the rest aren't filled is that we haven't reached an agreement on how to abbreviate the other stages. Apologies for this.

**Comment by ronaldtse** [comment]
When I said "EVERY" I only meant "wip", "preliminary" and "public". The rest don't need iterations.

**Comment by ronaldtse** [comment]
WIP draft: "WD"
Preliminary draft: "PreD" or "LD" or whatever
Public draft: "PD"

**Comment by opoudjis** [comment]
This is a new ticket, and since the spec for it is clearly not in place, I'm not holding up this ticket for it.

**Comment by opoudjis** [comment]
> Only a public draft will be available via the NIST website, so the draft author must be able to specify this.

That will be done by either YAML in Asciidoctor, or by document identifier with pre-formatted title; in either case, the author is going to have to specify the full IDs of any documents they cite, and include the draft abbreviation in the identifier. (WIP and Prelim abbreviations will simply not be fetched from NistBib. Public drafts will be, so @andrew2net, this becomes your problem now too (though it was clearly inevitable). I will make a ticket.

**Comment by ronaldtse** [comment]
> That will be done by either YAML in Asciidoctor, or by document identifier with pre-formatted title; 

And AsciiBib 👍
