### ISSUE TITLE
Iterations and Stages

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-nist#117]
WIP, Preliminary, and Public stages can all have iterations.

Presumably, the initial iteration of WIP and Preliminary stage is not specified as "Initial WIP"/"Initial Preliminary" (unlike the Initial Public Draft, IPD),  but just "WIP"/"Preliminary".

The stages should all be abbreviated, not just Public Drafts as PD. 

WIP draft: "WD"
Preliminary draft: "PreD" or "LD" or whatever (???)
Public draft: "PD"

This all needs NIST confirmation before it is actioned.

**Comment by ronaldtse** [comment]
> Presumably, the initial iteration of WIP and Preliminary stage is not specified as "Initial WIP"/"Initial Preliminary" (unlike the Initial Public Draft, IPD), but just "WIP"/"Preliminary".

Yes.

> Preliminary draft: "PreD" or "LD" or whatever (???)

This is the one we couldn't settle on.

All the rest are confirmed.

**Comment by opoudjis** [comment]
I'm doing PreD by fiat, because LD is not intuitive.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !

**Comment by opoudjis** [comment]
I am injecting the new abbreviations in the DRAFT prefix on the title page, because there's no good reason why one stage's abbreviation should be injected and not another.
