### ISSUE TITLE
HTML ToC contains empty anchors that do not point anywhere

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#118]
The HTML ToC contains empty sections right after the Authority section.

<img width="307" alt="Screen Shot 2019-05-08 at 9 36 20 PM" src="https://user-images.githubusercontent.com/11865/57421359-7669d500-71d9-11e9-8bec-8afb1fe510e8.png">

We need to not generate them.

**Comment by opoudjis** [comment]
There is a more general issue here, which is that the ToC is grabbing all h1, h2 instances, including empty ones, but also prefatory ones; you're seeing that in the sample new pages, with "superseding document" and "authority".

I will suppress empty headings, but I'm also going to suppress those prefatory instances, for consistency with Word ToC.
