### ISSUE TITLE
HTML version right side requires additional margin

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#119]
Right now, on the cover page, the NIST logo on the right does not have any margin with the browser border. There used
[NIST.SP.800-116r1.html.zip](https://github.com/metanorma/metanorma-nist/files/3159956/NIST.SP.800-116r1.html.zip)
 to be a margin.

1. We need some margin around the logo (top, right). 

<img width="768" alt="Screen Shot 2019-05-08 at 9 32 48 PM" src="https://user-images.githubusercontent.com/11865/57421208-d4e28380-71d8-11e9-99ad-d63c56b4cd27.png">

In addition, somehow you are allowed to scroll to the right, but the whitespace is empty.

<img width="824" alt="Screen Shot 2019-05-08 at 9 33 10 PM" src="https://user-images.githubusercontent.com/11865/57421225-e1ff7280-71d8-11e9-9724-fb3ee8a3fd98.png">

Attached is the HTML file the screenshots came from. 

@pierrefortier can you please help? Thanks!

@opoudjis will need the DIFF to know which lines to fix. Thanks!

**Comment by ronaldtse** [comment]
Ping @pierrefortier , thanks!

**Comment by opoudjis** [comment]
ping @pierrefortier

**Comment by pierrefortier** [comment]
So sorry for the delay! I have made the requested fixes:

[NIST.SP.800-116r1.html.zip](https://github.com/metanorma/metanorma-nist/files/3217273/NIST.SP.800-116r1.html.zip)

**Comment by opoudjis** [comment]
@ronaldtse, once you approve, I will implement

**Comment by ronaldtse** [comment]
@pierrefortier this looks good, thanks! @opoudjis please help proceed, thanks!
