### ISSUE TITLE
Create sample bibdata for Relaton XML/JSON web API

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#121]
This issue is to create a sample NIST bibdata that should be returned by a JSON web API.

Ping @opoudjis

**Comment by opoudjis** [comment]
[800-116.json.zip](https://github.com/metanorma/metanorma-nist/files/3177435/800-116.json.zip)

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
