### ISSUE TITLE
Confirmation of NIST document stage abbreviation

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#122]
Stemming from #117 , we have confirmed the abbreviations:

* Internal draft: ID
* WIP draft: WD
* Preliminary draft: PreD
* Public draft: PD
* ERB (Editorial Review Board) draft: RD (Review Draft)

This task is to address any gaps (we didn't have RD before).

**Comment by opoudjis** [comment]
Done in #123 (and it's AD Approval Draft now)

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
