### ISSUE TITLE
Allowing iterations in all document draft stages

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#123]
The iterations: `{I, 2, 3, ... n, F}` apply to all draft stages.

This issue is to ensure we allow this. Thanks @opoudjis !

<img width="963" alt="Screen Shot 2019-05-15 at 2 46 48 AM" src="https://user-images.githubusercontent.com/11865/57723679-b0e0df80-76bb-11e9-832a-a8adf8714c98.png">

**Comment by opoudjis** [comment]
We only allowed them for WIP, Prelim, Public. 

I need you to (a) double confirm that draft-internal has iterations; (b) provide me a name for NIST ERB review, which is *completely new* as a distinct NIST phase. That's why you still have it brackets there. I can't give you an RD if there is no corresponding review phase specified in the source, and at the moment there isn't.

**Comment by ronaldtse** [comment]
@opoudjis 

(a) It has been confirmed, that's why it was in the official presentation. `draft-internal` takes iterations.

(b) Originally we wanted to call the NIST ERB Review draft a "draft-review", but since there is already a "review" stage it makes things complex. Maybe "draft-approve", the "Approval Draft", "AD" works better. Let me confirm.

**Comment by ronaldtse** [comment]
@opoudjis confirmed.

NIST ERB Review stage (ISO stage code 50):

* draft stage name "Approval Draft"
* draft stage abbreviation "AD"
* stage code "draft-approval"
* iterations: "{I, 2, 3, ... n, F}AD"

**Comment by opoudjis** [comment]
More things to confirm:

At the moment the uniterated drafts do not have a draft abbreviation appended to them, other than IPD. I need you to also confirm that all draft stages on their first appearance will have an initial iteration label: IWD, IPreD, IPD, IAD, IID. I find it very hard to believe that is what is intended.

**Comment by opoudjis** [comment]
I've added draft-approval in rendering processing, but need answer to the foregoing.

**Comment by ronaldtse** [comment]
> At the moment the uniterated drafts do not have a draft abbreviation appended to them, other than IPD. I need you to also confirm that all draft stages on their first appearance will have an initial iteration label: IWD, IPreD, IPD, IAD, IID. I find it very hard to believe that is what is intended.

True. There is only precedent for IPD. I suspect we can forego the "I" character for the rest. Let me confirm.

**Comment by ronaldtse** [comment]
@opoudjis confirmation:

> For public drafts, we should keep IPD since it is a “real thing” that has already been in use. 

For the rest we can adopt ISO style.

> Internal Draft:    ID, 2ID, 3ID, …, FID
> WIP Draft:           WD, 2WD, 3WD, …, FWD
> Prelim Draft:      PreD, 2PreD, 3PreD, …, FPreD
> Approval Draft: AD, 2AD, 3AD,…, FAD

**Comment by opoudjis** [comment]
In that case, nothing more to fix.
