### ISSUE TITLE
Docidentifier type change

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-nist#124]
#19 has arisen as an issue in a NIST document cited in a non-NIST document: the document identifier for `<docidentifier type="nist">White Paper (DRAFT)</docidentifier>` is being rendered  as `nist White Paper (DRAFT)`.

The default in the rendering of document identifiers is to prefix the docidentifier type to the docidentifier content: so `<docidentifier type="CSD">123</docidentifier>` => `CSD 123`.

This is not applicable to all docidentifiers. For example, the prefix for ISO identifiers is formed by concatenating the abbreviations of the publishing agencies, with the ISO prefix always coming first. And using the type is a poor default.

Nonetheless, the simplest thing to address this is to change the default type of NIST identifiers, from `nist` to `NIST`. This will need to be done in both metanorma-nist (me) and relaton-nist (@andrew2net).

**Comment by ronaldtse** [comment]
@opoudjis in addition, I noticed that a citation to that particular NIST document creates this render:

<img width="137" alt="image" src="https://user-images.githubusercontent.com/11865/58432150-8b080180-80e3-11e9-8453-7c387af6277f.png">

It should be rendered as:
* "NIST Framework for Improving Critical Infrastructure Cybersecurity, Version 1.1, Clause ID.AM-1"

**Comment by opoudjis** [comment]
No "by the ways", Ronald. That confuses the ticket. Raise new tickets, and give context. Is this CSD citing NIST again?

Note that outside of NIST, all Metanorma gems are solely using the document Identifier fetched from relaton, and the title.

I don't know yet what's in the title fetched from NIST. I know that there is no way on earth Metanorma is going to pay any attention to version numbers in generating references, unless they are part of the title. That functionality just doesn't exist yet outside of metanorma-nist.

**Comment by opoudjis** [comment]
... actually, I have a horrible suspicion you've just asked something even more unreasonable. That Metanorma put not the document identifier in a citation, but the document title.

Citations in Metanorma are rendered as document identifier + location. That is it, and that's the behaviour you're seeing. If you want something more elaborate for a particular flavour, you have to ask for it, and wait for a few months for someone to implement it. And for me to tell you what an awful idea it is. (What next, "ibid"s?)

**Comment by ronaldtse** [comment]
If you took the time to read the issue, "Version, 1.1" is part of the title.

**Comment by opoudjis** [comment]
Making the title the document identifier is the least bad option, since there is no overt genuine identifier. But making the title the document identifier is... awful.

**Comment by opoudjis** [comment]
Ok, raising separate ticket for Andrej

**Comment by opoudjis** [comment]
.... hang on. https://github.com/metanorma/relaton-nist/issues/19 seems to indicate that the title is *already* being used as an identifier, because that is what the reference is retrieved by. Is that the case, @andrew2net? If so, just ensure that it is propagated into the Relaton XML returned (with the comma before "Version" put back in.)
