### ISSUE TITLE
(URGENT) Generated Word document (and HTML) not showing NIST/DoC logos in Windows

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#126]
A user reported that in Windows Word, the NIST/DoC images aren't showing. This is probably related to https://github.com/metanorma/metanorma-ogc/issues/36 . 

@CAMOBAP795 can you please help debug / fix this? Thanks!

**Comment by ronaldtse** [comment]
@CAMOBAP795 this issue apparently exists in the HTML form. Can you please help fix this ASAP? Thanks!

**Comment by ronaldtse** [comment]
Maybe it is related to the way Base64 encoding works on Windows (as with https://github.com/metanorma/metanorma-ogc/issues/36 ).

The same change needs to be made to gems that include logos, I believe it's only metanorma-csand right now. @opoudjis can you help confirm? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis 

I have found it only in:
 - `isodoc` - https://github.com/metanorma/isodoc/pull/104
 - `metanorma-standoc` - but it looks ok https://github.com/metanorma/metanorma-standoc/blob/master/lib/asciidoctor/standoc/blocks.rb#L220

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 , then can we confirm that Windows image generation is fully functional now? We're still missing the test?

**Comment by ronaldtse** [comment]
And the issue for the test is located here: https://github.com/metanorma/html2doc/issues/26 . Closing this in favor of that.

**Comment by ronaldtse** [comment]
Ping @CAMOBAP795 , is this issue fixed for NIST (and CSA for CSAND gem) logo inclusion? Both flavors include the logo. Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse sorry didn't test it for CSA for CSAND, can you suggest a fast way to test it?

**Comment by ronaldtse** [comment]
You can try this document: https://github.com/metanorma/csa-caiq for CSA (CSAND is just the alias to CSA)

**Comment by CAMOBAP795** [comment]
@ronaldtse on it

**Comment by CAMOBAP795** [comment]
@ronaldtse Sorry forgot to update, I have checked `metanorma/csa-caiq` with updated html2doc@0.8.11 I can confirm that it works

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 !
