### ISSUE TITLE
When in a NIST document, do not require reference prefix

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#127]
In a NIST document, when the anchor is a NIST document but did not specify so, this error will show:

```
FIPS140 does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
FIPS140 does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
FIPS180 does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
FIPS180 does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
FIPS197 does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
FIPS197 does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
FIPS198 does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
FIPS198 does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
FIPS202 does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
FIPS202 does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
...
SP800-38B does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
SP800-38B does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
SP800-57 does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
SP800-57 does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
SP800-90A does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
SP800-90A does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
SP800-90C does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
SP800-90C does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
SP800-107 does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
SP800-107 does not have a recognised prefix: IEC, ISO, IETF, CN, NIST
```

We should not need to give the prefix if the document type already provides that "NIST" prefix. Thanks!

**Comment by andrew2net** [comment]
@ronaldtse how do you get these errors?

**Comment by opoudjis** [comment]
Wait. 

A relaton code reference is recognised as NIST if it has the NIST prefix; having the SP prefix is not enough, and I don't want to start idiosyncratically having different gems do different things with prefixes. 

I dispute that this is a bug.

**Comment by opoudjis** [comment]
And if there will be a fix, it is certainly not in relaton at all.  SP would only be recognised as a NIST prefix within a NIST document,  so the fix would be in the NIST gem. 

But again,  I do not believe we should "fix" this.  And in any case, with no space between the prefix and number, these are already malformed as far as relaton is concerned. 

Andrej, please do not action this yet.  (You are still working on relaton refactor, after all.)

**Comment by andrew2net** [comment]
@opoudjis I don't get any errors when trying to get these codes in `relaton-nist`, but doing same with 'relaton` gives me these errors.

**Comment by opoudjis** [comment]
I'm not investigating this yet, but that may be because the NIST gem supplies any missing "NIST" prefix, if it recognises SP or NISTIR as NIST prefixes. relaton on its own is a generic tool, so it certainly cannot make the assumption that SP is a NIST prefix, and it would be a grievous error to make it do so. (Given how many prefixes GB uses for its various sector standards, I wouldn't be surprised if SP already turns up there.)

NIST can assume that SP = NIST SP. Other SDOs cannot.

**Comment by andrew2net** [comment]
@ronaldtse @opoudjis so we don't have to add SP or FIPS prefixes, do we? If so then NIST references should start with NIST.

**Comment by ronaldtse** [comment]
I don't think this issue is fixed yet. As mentioned, the problem is in metanorma-nist. When it sees "SP" and "FIPS" it should automatically prefix "NIST" for Relaton to search the reference.

**Comment by opoudjis** [comment]
Fixing this, but note that a space is expected between `SP` or `FIPS` and the document number.
