### ISSUE TITLE
`tzinfo-data` gem requirement not working on Windows through Bundler

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#128]
While this line is implemented in #114 :

https://github.com/metanorma/metanorma-nist/blob/29338d317604363e1e65f696ef6255e67e5d9c55/metanorma-nist.gemspec#L31

It is apparently not working for a user. The user reports that usage of `metanorma-nist` at version 0.0.9 still throws the `No source of timezone data could be found. (TZInfo::DataSourceNotFound)` error. The user is using `bundle exec metanorma` using a Gemfile that was created on a macOS (which clearly won't include `tzinfo-data`).

`metanorma-nist` 0.0.9 has already included the fix above as mentioned in the release notes:
https://github.com/metanorma/metanorma-nist/releases/tag/v0.0.9

1. We need a quick fix for this. I propose we include the dependency for all platforms without the `if` statement.
2. We need a long term fix for this. I propose we move this dependency Metanorma-wide since it may be used elsewhere.

**Comment by ronaldtse** [comment]
In fact I don't think this scenario is supported by Bundler.

Related:
* https://github.com/bundler/bundler/pull/6247
* https://github.com/bundler/bundler/issues/6233

**Comment by opoudjis** [comment]
The metanorma-nist gem is still not getting released until the relaton refactoring is done, because it clearly impacts it; there has been refactoring of isodoc and metanorma-standoc as well. And this is supposed to be a major release.

The quick fix is straightforward enough; tzinfo-data is harmless as an unused dependency on Mac.

**Comment by CAMOBAP795** [comment]
I just checked https://www.ruby-forum.com/t/build-a-ruby-gem-and-conditionally-specify-dependencies/215953

Looks like approach which was implemented by me 29338d317604363e1e65f696ef6255e67e5d9c55 doesn't work at all and looks like there is no `gemspec` based solution

Proposed solution:
 - add this info to https://www.metanorma.com/software/metanorma-cli/docs/installation/#installation-notes-for-windows
 - Update chocolatey script to install `tzinfo-data` gem

@ronaldtse how do you think?

**Comment by ronaldtse** [comment]
@CAMOBAP795 as I said, just include `tzinfo-data` as a dependency in the gem spec.

**Comment by ronaldtse** [comment]
Jekyll uses these lines, but I these can't propagate in `gemspec`:

https://github.com/jekyll/jekyll/blob/08b04aa337cfe3134d3791fd6f63134ba37a7dba/Gemfile#L82-L86

**Comment by ronaldtse** [comment]
@opoudjis should we add the `tzinfo-data` in the `gemspec` of metanorma-standoc (or another place)? It's surely getting used more than just here.

**Comment by CAMOBAP795** [comment]
@ronaldtse because https://github.com/metanorma/metanorma-nist/issues/129 merged I think we can close this one

**Comment by ronaldtse** [comment]
Agree!

**Comment by opoudjis** [comment]
@ronaldtse, @CAMOBAP795: If you make a commit to a Metanorma gem, include the issue that it relates to in the commit message. I compile the release log from those commits, and I should not have to hunt through the issues to work out why commits happened.

**Comment by CAMOBAP795** [comment]
@opoudjis good point, I will follow it starting from my next commits
