### ISSUE TITLE
HTML version missing "Subtitle"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#131]
Word:
<img width="681" alt="Screen Shot 2019-06-19 at 1 55 11 AM" src="https://user-images.githubusercontent.com/11865/59707510-5a743d00-9235-11e9-8957-c02cea23588b.png">

HTML:
<img width="523" alt="Screen Shot 2019-06-19 at 1 55 36 AM" src="https://user-images.githubusercontent.com/11865/59707499-56481f80-9235-11e9-990b-8d39804bfecf.png">

**Comment by opoudjis** [comment]
Huh. For some reason, the HTML CSS disables display of subtitles. Undoing.
