### ISSUE TITLE
Citing NIST document inside NIST document will cause crash

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#132]
```adoc
* [[[ref_sp,NIST SP 800-187]]],	Cichonski JA, Franklin JM, Bartock M (2017) _Guide to LTE Security_. (National Institute of Standards and Technology, Gaithersburg, MD), NIST Special Publication (SP) 800-187.
https://doi.org/10.6028/NIST.SP.800-187
```

Reason: reference rendering code can't accept "month with year", it only uses "Date/DateTime.parse" which will fail on this.

<img width="403" alt="Screen Shot 2019-06-19 at 1 59 06 AM" src="https://user-images.githubusercontent.com/11865/59707743-d3739480-9235-11e9-9e2b-be4dedf48a4a.png">

**Comment by ronaldtse** [comment]
And this also occurs with RFC documents, which are also published with Month+Year.

**Comment by ronaldtse** [comment]
Here's where they crash:

https://github.com/metanorma/metanorma-nist/blob/96bcb37aed55a68dfe31798aacdf90638ed81082/lib/isodoc/nist/render.rb#L258-L271

**Comment by ronaldtse** [comment]
While this issue is fixed, we need to add a test case.

**Comment by opoudjis** [comment]
Addressed in rspec
