### ISSUE TITLE
When `formattedref` is provided in a Relaton file, use it

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#134]
https://github.com/metanorma/metanorma-nist/blob/96bcb37aed55a68dfe31798aacdf90638ed81082/lib/isodoc/nist/render.rb#L164-L169

This code is just wrong because `r` is never defined.

We need to add a test case to ensure the `formattedref` is actually used!

**Comment by ronaldtse** [comment]
While this issue is fixed, we need to add a test case.

**Comment by opoudjis** [comment]
The fix makes no sense at all where it is. If fomattedref is present, it does not substitute the series, it substitutes  the entire reference.

**Comment by opoudjis** [comment]
In fact, there is already code that deals with formattedref in the calling function.

I have no idea what you were fixing here, @ronaldtse, but it looks like you were fixing the wrong thing. Which is why you should not be hastily fixing code, and waiting for me to become available.

**Comment by opoudjis** [comment]
I am undoing the code fix you put in here.

**Comment by ronaldtse** [comment]
https://github.com/metanorma/metanorma-nist/commit/61aa40fef79b18ba2c6df0236ca2ecad2d311ff5

As mentioned, this line:

```ruby
f = s.at("./formattedref") and return r.text
```

Referred to a nonexistent `r` in this context. There was a reason for the fix.

**Comment by opoudjis** [comment]
Worked it out.
