### ISSUE TITLE
Add GitLab CI to GitLab templates

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#136]
@CAMOBAP795 we have a separate template repository at GitLab . Can you please help add GitLab CI for that repo so we know it is buildable? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse PR https://gitlab.com/metanorma/mn-templates-nist/merge_requests/1 blocker by https://github.com/metanorma/metanorma/pull/70

**Comment by CAMOBAP795** [comment]
@ronaldtse ready for merge https://gitlab.com/metanorma/mn-templates-nist/merge_requests/1 could you please proceed
