### ISSUE TITLE
Update samples to display web accessibility features

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#142]
alt, etc.

In the samples document repo.

**Comment by opoudjis** [comment]
Which I am deeming as being:

* alt text for images, `image::xxx[text]`
* alt text for hyperlinks: https://github.com/metanorma/metanorma-nist/issues/108, `http://www.example.com[text,title=alttext]`
* alt text for tables: https://github.com/metanorma/metanorma-nist/issues/109, `[alt=Text] |===`

**Comment by opoudjis** [comment]
Just realised that I have not yet implemented longdesc on tables. This is in fact a problem, given the incompatibility of HTML 4 and HTML 5.

**Comment by opoudjis** [comment]
The sample documents do not seem to have put alt text on hyperlinks, with the sole exception of the boilerplate use of `<a href="https://csrc.nist.gov/publications"
title="NIST Computer Security Division publications">https://csrc.nist.gov/publications</a>` in NIST SP 800 126r3. Given that this is for illustrative purposes only, I'm happy to inject it into the boilerplate for documents.
