### ISSUE TITLE
Table summaries

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-nist#143]
HTML 4, and Word, support summary attributes on tables: extensive descriptions of tables, that can appear along side short descriptions (the latter being the `table/@title` attribute).

HTML 5 does NOT support `table/@summary`, and has several quite awkward workarounds: https://www.w3.org/WAI/tutorials/tables/caption-summary/ , https://www.davidmacd.com/test/details.html . The most straightforward option is to embed the summary inside the table caption (and make it not visible in HTML output).

NIST has used summary attributes on some of its tables. We will be expected to support this.

https://github.com/metanorma/metanorma-standoc/issues/74 proposes that we add longdesc for images: this is an HTML 5 attribute. This makes it asymmetrical with tables, which do not have an equivalent summary attribute in HTML 5.

I propose we add `longdesc` in BasicDoc to tables as well as images. In HTML 4 and Word HTML, this renders as the summary attribute of tables. In HTML 5, we will insert this into `<caption>`, in a non-visible span. We are currently not using `<caption>` at all, and are treating titles as a separate paragraph. We may yet be called on to make titles into captions; we will deal with that if and when we do.

None of the HTML 5 solutions are great, and it seems that screenreaders do behave much better with the HTML 4 table summary attribute; but we are now required to generate HTML 5 valid code.

**Comment by ronaldtse** [comment]
@opoudjis `longdesc` does not seem to be a semantic element. How do you suppose we resolve this? Could we implement a semantic element (with name of your choosing) that serializes into HTML 4 `longdesc` and HTML5 `caption`?

"table summary"? "table caption" (which is clearly not detailed like a summary)?

**Comment by opoudjis** [comment]
....

longdesc is a semantic element by definition; I've decided it is one. It serialises into HTML 4 `table/@summary` (not longdesc! In HTML, that is only an image attribute); and into HTML 5 `table/caption/span[@style="display:none"]`.

Implemented.

**Comment by opoudjis** [comment]
Rename longdesc to summary
