### ISSUE TITLE
CSWP Word template footnote seems to be indented from 2nd row onwards

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#152]
A picture is worth a thousand words. This can be found in NIST.CSWP.01262018.adoc of mn-samples-nist (branch: new-samples).

<img width="590" alt="image" src="https://user-images.githubusercontent.com/11865/66321157-bda7ed80-e952-11e9-8eb7-b72d3f61b235.png">

**Comment by opoudjis** [comment]
That is exactly how the CSWP template styles footnotes. So wontfix. @ronaldtse to check if that is intentional.

**Comment by ronaldtse** [comment]
Thanks for checking, I will confirm with them.

**Comment by ronaldtse** [comment]
@opoudjis confirmed to be a template bug, we could fix it, or not if it is too complex.
