### ISSUE TITLE
`docidentifier/nist-mr` is broken

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#163]
From document NIST.SP.800-116r1.

<img width="709" alt="Screen Shot 2019-12-05 at 12 26 55 PM" src="https://user-images.githubusercontent.com/11865/70204179-8723fe80-175a-11ea-8d6b-5de061df6667.png">

Even the specs are broken:
https://github.com/metanorma/metanorma-nist/search?utf8=✓&q=nist-mr&type=

<img width="633" alt="Screen Shot 2019-12-05 at 12 26 17 PM" src="https://user-images.githubusercontent.com/11865/70204158-71163e00-175a-11ea-8578-c36f78090c8d.png">

<img width="631" alt="Screen Shot 2019-12-05 at 12 26 26 PM" src="https://user-images.githubusercontent.com/11865/70204164-76738880-175a-11ea-8bed-30f2e98c630a.png">

The `nist-mr` identifier should be similar with the DOI.

This is blocking machine determination of which PDF layout is to be used in mn-native-pdf. It should really be affecting `isodoc`, unless there's something funny going on there...

**Comment by ronaldtse** [comment]
And in fact, the `doctype` is not set in MN NIST XML...

Despite this being set in code:
```
      def doctype(node)
        node.attr("doctype") || "sp-800"
      end
```

In the XML it's set as this regardless if it is a CSWP or SP 800.

```xml
  <ext>
    <doctype>standard</doctype>
  </ext>
```

**Comment by opoudjis** [comment]
The differentiation between CSWP and SP-800 is already captured under "series". doctype is for intellectually defensible differences between document types, such as standards vs white papers. It is not a place to repeat information from series. If you have a coherent ontology of NIST publications that is distinct from series, let me know; but this is not it.

**Comment by opoudjis** [comment]
docnumber has been omitted in the implementation of nist-mr, https://github.com/metanorma/metanorma-nist/issues/88. Fixing.
