### ISSUE TITLE
Define `nist-mr` scheme properly

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#168]
The `nist-mr` scheme should be a structured identifier that allows machine reading. It must be possible to use this scheme to generate the PubID, which is for human-consumption, possibly be used for the DOI ID, and as a filename.

## PubID syntax (human-readable)

The PubID syntax is:
* "{series} {stage} {report number}{part}{edition}({translation})/{update} {update number}:{update year}"

From the PubID elements we can define the MR ID elements.

## MR ID elements

In MR ID, we use the separator of `.`.

{originator}: always `NIST`.

{series}:
* "NIST" followed by abbreviation of series name:
  * NIST SP: Special Publication
  * NIST IR: Interagency/Internal Report
  * NIST HB: Handbook
  * NIST TN: Technical Note
* => MR: use `{series abbr}` (EXAMPLE `NIST.SP` since originator is `NIST`)

{stage}:
* In PubID, Final publications do not show stage code. However, in MR ID we can mark those as "PUB"

* Some series (e.g. SP 800) have additional stages, which includes "iteration" with the "stage":
  * Public Drafts: IPD (Initial Public Draft), 2PD, ... FPD (Final Public Draft). 
  * Work-in-Progress Draft: WD
  * Preliminary Draft: PreD
  * Final: PUB
* => MR: we can call this `{stage}[-{iteration}]`: e.g. `PD-1`, `PD-2`,... `PD-F`, `PUB`. The optional iteration can be detected with the presence of `-`. (without iteration it points to the latest existing iteration)

{report number}:
* Depends on the series:
  * {sequence number}
  * {subseries}-{sequence number}
  * {sequence number}-{volume}
  * {sequence number}-{edition}
  * {subseries}-{sequence number}-{edition}
  * etc.
* Note that we are semantically motivated, not rendering motivated:
  * In the case where the "part" is an alphabetical character that forms part of the identifier, such as "800-53A" or "800-57pt1" or "800-73-4", we must preserve this identifier in this "report number". We have to duplicate the part portion to `{part}` (`pt-A`, `pt-1`, `pt-4` respectively).
  * In the cases when `edition` or `volume` forms part of the report number, we duplicate those portions in `{edition}` and `{version}` respectively. 
* => MR: use the report number directly

{part}:
* "Parts" are marked by these prefixes, followed by Arabic numerals and/or alphabetic characters:
  * Part: `pt`
  * Volume: `v`
  * Section: `sec`
  * Supplement: `sup`
  * Index: `indx`
* => MR: use `{part prefix}-{part number}`, e.g. `pt-1`, `pt-B`

{edition}:
* In PubID the edition marked by these prefixes, followed by Arabic numerals and/or alphabetic characters
  * Edition: `e`
  * Revision: `r`
  * Version: `ver`
* => MR: use `{edition prefix}-{edition number}`, e.g. `ver-2`. For those that don't have edition, we mark them as `ed` (without number).

{translation}:
* In PubID, a non-English translation is marked with a three-letter ISO 639-2 code.
* In MR ID we can always mandate the language code.
* => MR: use `{lang code}`, e.g. `eng`, `esp`
  * If it is a bilingual document (e.g. side by side), the language codes can be separated by `,`
  * always detectable because they are 3-letter codes.

"{update} {update number}:{update year}":
* If the document includes updates (i.e. corrigenda applied), this element applies
* The edition portion will be appended by "/Upd and {update number}
* In PubID the update number is followed by ":" and the year of that update (yyyy).
* {update number} is indicated by sequential Arabic numerals, starting with "1"
* => MR: use `upd-{update number}:{update year}`, e.g. `upd-3:2020`

## Full MR ID

We define the NIST-MR ID scheme to be: a concatenation of these elements in machine-parsable form using the `.` as a separator. Empty elements are omitted.

* `NIST`
* `{series abbr}`
* `{stage}` (optional, possible to detect absence since the first report number character is always numeric)
* `{report number}`
* `{part}` (optional, possible to detect absence since `{part}` is uniquely prefixed)
* `{edition}` (optional, possible to detect absence since `{edition}` is uniquely prefixed)
* `{translation}` (always detectable because these are 3-char codes)
* `{update} {update number}:{update year}` (optional, possible to detect absence since `{update}` is uniquely prefixed)

This scheme allows us to regenerate (roundtrip) the readable PubID fully.

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-nist/issues/167#issuecomment-569608851_

**Comment by ronaldtse** [comment]
We can re-use the concepts from https://tools.ietf.org/html/rfc5141 too!

**Comment by ronaldtse** [comment]
## Sample MR for PubID samples (samples from PubID draft 0.6)

### SP 800 series

|PubID | MR |
|--|--|
| NIST SP 800-40r3 | `NIST.SP.800-40.r-3.eng`
| NIST SP 800-45ver2 | `NIST.SP.800-45.ver-2.eng`
| NIST SP 800-53r4/Upd 3:2015 | `NIST.SP.800-53.r-4.eng.upd-3:2015`
| NIST SP IPD 800-53r5 | `NIST.SP.PD-1.800-53.eng.r-5`
| NIST SP 800-53Ar4/Upd 1:2014 | `NIST.SP.800-53A.pt-A.r-4.eng.upd-1:2014`
| NIST SP 800-60v1r1 | `NIST.SP.800-60.v-1.r-1.eng`
| NIST SP 800-57pt1r4 | `NIST.SP.800-57pt1.pt-1.r-4.eng`
| NIST SP 800-73-4/Upd 1:2016 | `NIST.SP.800-73-4.pt-4.eng.upd-1:2016`
| NIST SP 2PD 800-188 | `NIST.SP.PD-2.800-188.eng`

### SP 1800 series

|PubID | MR |
|--|--|
| NIST SP 2PD 1800-13B | `NIST.SP.PD-2.1800-13B.pt-B.eng`
| NIST SP PreD 1800-19B | `NIST.SP.PRED.1800-19B.pt-B.eng`

### NIST IR series

|PubID | MR |
|--|--|
| NIST IR 8011v3 | `NIST.IR.8011.v-3.eng`
| NIST IR 8204/Upd 1:2019 | `NIST.IR.8204.eng.upd-1:2019`
| NIST IR 8115(spa) | `NIST.IR.8115.spa`

### Other NIST Series

|PubID | MR |
|--|--|
| NIST HB 130e2019 | `NIST.HB.130.e-2019.eng`
| NIST SP 1041r1/Upd 1:2012 | `NIST.SP.1041.r-1.eng.upd-1:2012`
| NIST NCSTAR 1-1Cv1 | `NIST.NCSTAR.1-1C.v-1.eng`

**Comment by opoudjis** [comment]
Adding document attributes to capture part number components, so that they can be worked into ids.

There are some errors in the spec:

* PUB is simply not used in the samples above, so I am ignoring the suggestion to use it.
* Parts are optional, and there can be more than one part.
* Ignoring "For those that don't have edition, we mark them as `ed` (without number)", since it is not used in the samples above.

**Comment by opoudjis** [comment]
Also adding support for `:update:`, to published ID.
