### ISSUE TITLE
Remove RFC 6350 from examples

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#180]
Remove RFC 6350 from examples. It is not for this flavor and causing confusion such as in https://github.com/metanorma/metanorma-un/issues/43#issuecomment-603679953 . Thanks!

* Replace it with some fictitious document (see mn-samples-nist for inspiration).

**Comment by opoudjis** [comment]
Will not replace; global approach is just to refer README to samples repo

**Comment by ronaldtse** [comment]
@opoudjis but is the global approach to test against mn-samples-*?

**Comment by opoudjis** [comment]
Yes, and where they don't exist, they should.

**Comment by ronaldtse** [comment]
Agreed.
