### ISSUE TITLE
Tables in generated PDFs don't have any border

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-nist#182]
Coming from "Review NIST document output" issue in https://gitlab.com/metanorma/mn-native-pdf-nist/-/issues/4

Tables are rendering without any border in PDF format.

### Example:

Original source:
![table-source](https://user-images.githubusercontent.com/33627611/77811356-19387580-7070-11ea-8137-093fa8a04c69.PNG)

Code:
`````
[cols="a,a,a,a,a,a",options="header",alt=ARF Relationships]
|===
| Relationship | Condition | Cardinality | Definition | Subject | Object

| arf-rel:isAbout | None | One for each component report | Each report is reporting about the asset | Component report | Target asset
| scap-rel:checkContext | Benchmark report exists | One for each check component report (OVAL or OCIL) | Each check report is reporting in the context of the benchmark report | Check component report | Benchmark component report
| scap-rel:fromSource | Report request exists | One for each component report | Each component report was generated from the SCAP source content | Component report | Report request
| scap-rel:associatedWith | OVAL variables report is provided | One for each OVAL variables component report | Each OVAL variables report is associated with an OVAL result | Component report of OVAL variables | Component report of OVAL results
|===
`````

Generated PDF:
![table-generated](https://user-images.githubusercontent.com/33627611/77811377-2e150900-7070-11ea-9c4e-f74ea205c4ab.PNG)

**Comment by ronaldtse** [comment]
This relates to PDF layout so I've also posted here: https://gitlab.com/metanorma/mn-native-pdf-nist/-/issues/12

Thanks!

**Comment by opoudjis** [comment]
And it's nothing to do with me, so unassigning myself.

**Comment by manuel489** [comment]
Ok @opoudjis . Understood.

**Comment by Intelligent2013** [comment]
The table in original PDF https://metanorma.gitlab.io/mn-native-pdf-nist/documents/NIST.SP.800-126r3.pdf :
![image](https://user-images.githubusercontent.com/5559926/77857927-23da4280-7209-11ea-9cec-3a4148d6dcde.png)

looks similar to original DOC. Where do you see generated PDFs? Looks like we use different urls...

**Comment by manuel489** [comment]
@Intelligent2013 , I generated the PDF output locally. Maybe I'm running on an outdated gem. Let me check...

**Comment by manuel489** [comment]
I have fetched from metanorma-nist  (https://github.com/metanorma/metanorma-nist) directly and I'm still getting the same result :confused:

**Comment by Intelligent2013** [comment]
> I have fetched from metanorma-nist (https://github.com/metanorma/metanorma-nist) directly and I'm still getting the same result 😕

@manuel489 Looks like metanorma-nist generates PDF from html code. But code for PDF generating by XSL-FO found here: https://gitlab.com/metanorma/mn-native-pdf-nist

**Comment by opoudjis** [comment]
Right, the PDF code that @Intelligent2013 is working on has not been integrated into metanorma yet, and won't be until the font setup is completed.

**Comment by ronaldtse** [comment]
@manuel489 The newest PDF layouts are at https://github.com/metanorma/mn-native-pdf and https://gitlab.com/metanorma/mn-native-pdf-nist . The point is to get the layouts correct. It doesn't matter if correctness comes before or after integrates them.

**Comment by ronaldtse** [comment]
This issue has been resolved in PDF layout https://gitlab.com/metanorma/mn-native-pdf-nist/-/issues/12 . Closing.
