### ISSUE TITLE
Errata tables get shifted way to the right in DOC output

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-nist#186]
*Encoding sample:*

````
[preface]
== Errata
The following changes have been incorporated into Special Publication 800-53, Revision 4.

[errata]
|===
| Date | Type | Change | Pages

<.<| 05-07-2013 <.<| Editorial <.<| Changed CA-9 Priority Code from P1 to P2 in <<tabled2>>. <.<| D-3
<.<| 05-07-2013 <.<| Editorial <.<| Changed CM-10 Priority Code from P1 to P2 in <<tabled2>>. <.<| D-4
<.<| 05-07-2013 <.<| Editorial <.<| Changed MA-6 Priority Code from P1 to P2 in <<tabled2>>. <.<| D-5
<.<| 05-07-2013 <.<| Editorial <.<| Changed MP-3 Priority Code from P1 to P2 in <<tabled2>>. <.<| D-5
<.<| 05-07-2013 <.<| Editorial <.<| Changed PE-5 Priority Code from P1 to P2 in <<tabled2>>. <.<| D-5
<.<| 05-07-2013 <.<| Editorial <.<| Changed PE-16 Priority Code from P1 to P2 in <<tabled2>>. <.<| D-5
<.<| 05-07-2013 <.<| Editorial <.<| Changed PE-17 Priority Code from P1 to P2 in <<tabled2>>. <.<| D-5
<.<| 05-07-2013 <.<| Editorial <.<| Changed PE-18 Priority Code from P2 to P3 in <<tabled2>>. <.<| D-5
<.<| 05-07-2013 <.<| Editorial <.<| Changed PL-4 Priority Code from P1 to P2 in <<tabled2>>. <.<| D-6
<.<| 05-07-2013 <.<| Editorial <.<| Changed PS-4 Priority Code from P2 to P1 in <<tabled2>>. <.<| D-6
<.<| 05-07-2013 <.<| Editorial <.<| Changed SA-11 Priority Code from P2 to P1 in <<tabled2>>. <.<| D-6

...
`````

*DOC output:*
![errata-capture](https://user-images.githubusercontent.com/33627611/77839088-d4800d80-7147-11ea-8351-ae960740d459.PNG)

This issue is also tracked here: https://gitlab.com/metanorma/mn-native-pdf-nist/-/issues/16 

Thanks!

Sample file:
[errata-table-issue.zip](https://github.com/metanorma/metanorma-nist/files/4398226/errata-table-issue.zip)

**Comment by opoudjis** [comment]
isodoc Word styling needs to force the table attributes mso-table-lspace; margin-left; mso-table-rspace; margin-right; all to be 15cm, so that the table can fill the page correctly.

Which works when the page width is 15 cm, and not 16.5 cm, as it is in NIST.

I will have to do two things: see if I can parameterise page width in gems, for Word; and see if there is a better solution for table widths; this will blow up in landscape anyway.

**Comment by opoudjis** [comment]
Of the values, the large mso-table-lspace and rspace are from https://superuser.com/questions/728099/how-can-i-add-spacing-between-a-table-and-the-paragraph-immediately-after-it#comment1353888_728303 via https://github.com/metanorma/metanorma-iso/issues/242. They are a hack, and the hack should go for broke, and be larger than any plausible page width.

In fact, the whole attempt to autospace between tables has fallen afoul of the need to repeat titles in tables between pages, and was dispensed with in https://github.com/metanorma/metanorma-itu/issues/70. So I'm removing that kludge from isodoc.
