### ISSUE TITLE
Archived cover page: Need method to encode superseding document, withdrawal note and additional information

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#189]
From https://gitlab.com/metanorma/mn-native-pdf-nist/-/issues/1#note_319249439

![image](https://user-images.githubusercontent.com/11865/78678186-334d4000-791b-11ea-8c25-1494aed389b5.png)

**Comment by opoudjis** [comment]
I do not need to provide a method to encode superseding document, withdrawal note and additional information. I merely need to point @Intelligent2013 to where in the XML these fields are populated from.

This information is recoverable from the code, and I strongly encourage you to get familiar with the various isodoc/*/metadata.rb files; I strongly suspect I'm going to end up passing them to the XSLT as arguments anyway.

I am not going to convert dates from yyyymmdd format into Month Year, mmddyyyy, or MMMddyyyy format in the XML. No. Those are presentational variants, that do not belong in the XML. The XSLT can consume the metadata preprocessing I'm doing (whereby each of the following is a variable being passed to Liquid), or it's converting them in situ.

Withdrawn Publication: 
Series/Number: `//bibdata/docidentifier[@type = 'nist-long']`
Title: `//bibdata/title[@type = 'main']` (+ ":" + `//bibdata/title[@type = 'subtitle']`)
Publication Date(s): `//bibdata/date[@type = 'issued']` (formatted as Month Year) ; if `//bibdata/date[@type = 'confirmed']` then `(publication is current as of //bibdata/date[@type = 'confirmed'])` (formatted as mmddyyyy); elsif `errata` and `//bibdata/date[@type = 'updated']` then `(including updates as of //bibdata/date[@type = 'updated'])` (formatted as mmddyyyy)
Withdrawal Date: `//bibdata/date[@type = 'obsoleted']` (formatted as MMMddyyyy)
Withdrawal Note: `//bibdata/note[@type = 'withdrawal-note']`

Superseding Publication(s):
Series/Number: `//bibdata/relation[@type = 'obsoletedBy']/bibitem/docidentifier[@type = 'nist-long']`
Title: `//bibdata/relation[@type = 'obsoletedBy']/bibitem /title[@type = 'main']` (+ ":" + `//bibdata/relation[@type = 'obsoletedBy']/bibitem/title[@type = 'subtitle']`)
Author(s): `//bibdata/relation[@type = 'obsoletedBy']/bibitem/contributor[role/@type = 'author']/person/name/((forename || initials + surname) || completeName)` (joined with ";")
Publication Date(s): `//bibdata/relation[@type = 'obsoletedBy']/bibitem/date[@type = 'issued']` (formatted as Month Year)
URL/DOI: `//bibdata/relation[@type = 'obsoletedBy']/bibitem/uri[@type = 'doi'] or //bibdata/relation[@type = 'obsoletedBy']/bibitem/uri[@type = 'uri']`

Additional Information:
Contact: `//bibdata/contributor[role/@type = 'publisher']/organization/subdivision`
Latest revision of the attached publication: —
Related Information: `//bibdata/note[@type = 'additional-note']`
Withdrawal Announcement Link: `//bibdata/note[@type = 'withdrawal-announcement-link']`
