### ISSUE TITLE
Style of the TIP/WARNING boxes not fully filled with grey

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#194]
Earlier it was reported that generated NIST PDFs should have TIP/WARNING blocks with the white outline, because they were compared to the generated NIST DOCs. However, by comparing the documents with the original PDFs, it was noticed that TIP/WARNING boxes should be completely filled with grey color. 

Original:
![image](https://user-images.githubusercontent.com/55683568/79897729-68bd5780-840a-11ea-8f89-e290bdf3ead6.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/79897760-770b7380-840a-11ea-83f1-7d51f2fa821f.png)

From: https://github.com/metanorma/mn-samples-nist/issues/20

**Comment by opoudjis** [comment]
Yes, and I have been unable to work out how to do that.
