### ISSUE TITLE
Manual re-naming of cross-references doesn't work

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#195]
I noticed that re-naming cross-references doesn't work for NIST anymore. Syntax such as `<<subsection, S1>>` doesn't produce `[S1]`, rather `[Section x.y]`.

![image](https://user-images.githubusercontent.com/55683568/79896330-87225380-8408-11ea-9cd6-177b8827a3a0.png)

Example which illustrates this issue is attached.
[test_crossreferences.zip](https://github.com/metanorma/mn-samples-nist/files/4511670/test_crossreferences.zip)

From @anermina  https://github.com/metanorma/mn-samples-nist/issues/17

**Comment by opoudjis** [comment]
Bug in recent implementation of LocationStack. Introduced test to cover.
