### ISSUE TITLE
Pages do not render in Errata table with [errata] tag

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-nist#199]
When adding `[errata]` attribute before Errata table, page numbers are not rendered (last column).

Generated with `[errata]`:
![image](https://user-images.githubusercontent.com/55683568/79894965-7cff5580-8406-11ea-9a00-da1135426e21.png)

Generated without `[errata]`:
![image](https://user-images.githubusercontent.com/55683568/79894932-7244c080-8406-11ea-8ec8-e1e7445628e2.png)

Attached is an example which illustrates this issue.
[test_errata.zip](https://github.com/metanorma/mn-samples-nist/files/4511595/test_errata.zip)

**Comment by opoudjis** [comment]
NIST is hard coded to read pages only from a column with heading "pages"; you have "page" in the table.

There may be a task to create a more flexible syntax (cf. https://github.com/metanorma/metanorma-ogc/issues/152), but keys like "page" have to be entered accurately, whether as table headings or as YAML keys.
