### ISSUE TITLE
Broken HTML in ALL NIST SP documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#202]
There is something broken in the JS content that causes the TOC JS not to run:

e.g.: https://metanorma.gitlab.io/mn-samples-nist/documents/NIST.SP.800-116r1.covers.draft-public.html
<img width="1085" alt="Screen Shot 2020-05-15 at 12 22 06 PM" src="https://user-images.githubusercontent.com/11865/82011160-b1cd9800-96a6-11ea-8149-c774cf337704.png">

<img width="1072" alt="Screen Shot 2020-05-15 at 12 20 48 PM" src="https://user-images.githubusercontent.com/11865/82011088-83e85380-96a6-11ea-837e-6956ece523aa.png">

Here's the actual error:

<img width="771" alt="Screen Shot 2020-05-15 at 12 22 57 PM" src="https://user-images.githubusercontent.com/11865/82011196-d0cc2a00-96a6-11ea-8746-4d938d47ddaf.png">

Here you can see the "anchorjs" code is broken into two parts with an `</html>` close tag in the middle. This is a serious breakage.

This bug is likely to also occur in other flavors.

**Comment by opoudjis** [comment]
Yes, three year old bug, regex was used to insert the script, and it is misinterprets sequences that look like captures, such as `\'`. Updating anchor.js, and changing how script is inserted.
