### ISSUE TITLE
AsciiBib malfunction

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-nist#211]
Consider the following example:
````
[%bibitem]
=== RNP: A C library approach to OpenPGP
id:: RNP
contributor::
contributor:organization.name:: Ribose Inc.
contributor:organization.contact::
contributor:organization.contact.street:: Suite 1111, 1 Pedder Street
contributor:organization.contact.region:: Central
contributor:organization.contact.country:: Hong Kong
contributor:organization.contact.city:: Hong Kong
contributor:organization.contact.email:: open.source@ribose.com
contributor:organization.contact.uri:: https://www.ribose.com

````

which renders as

![Capture2](https://user-images.githubusercontent.com/33627611/84462297-ac7b5300-ac3c-11ea-81e0-602f9dc99957.PNG)

Contact information is missing, and, there is a "(NO ID)" in the result, even when an ID was set.

**Comment by opoudjis** [comment]
Both @manuel489  and @ronaldtse (https://github.com/metanorma/metanorma-nist/issues/209):

> when an ID was set.

An ID has emphatically NOT been set.

The problem with using asciibib is, you need to understand Relaton XML, which it maps to, and I'm sorry, but neither of you have here.

id is the anchor of the bibliographic entry. In a normal entry like

````
* [[[ref,ISO 123]]]
````

It is the `ref`. It is what you insert in `<<ref>>` to reference the entry.

It is NOT the document identifier, the "ISO 123" in the example above. That is entered as 

````
docidentifier:: RNP
````

and indeed preferably

````
docidentifier::
docidentifier.type:: Ribose
docidentifier.value:: RNP
````

Without an actual docidentifier, bad things happen in citations. The `* [[[anchor,docidentifier]]]` syntax actually forces you to always insert a docidentifier, which is a very good thing. Asciibib is freestyle, which means you aren't being forced.

id is distinct from docidentifier. You need to enter both.
