### ISSUE TITLE
Bibliography rendering of multiple authors contains stray whitespaces before commas

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#212]
<img width="894" alt="Screen Shot 2020-06-15 at 8 44 58 AM" src="https://user-images.githubusercontent.com/11865/84608358-a909f500-aee4-11ea-96cf-424eaa35ea73.png">

**Comment by opoudjis** [comment]
Now the authors are being ignored completely, because the markup in ACVP does not explicitly say they are authors. Fixing source.

**Comment by opoudjis** [comment]
NIST error: "initials" instead of "initial".

**Comment by ronaldtse** [comment]
Thanks @opoudjis , could you help check AVCP to see if that error in asciibib is still there (because of my change)?
