### ISSUE TITLE
Broken TOC and missing font?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#218]
This is from mn-samples-nist.

<img width="1171" alt="Screen Shot 2020-06-30 at 11 05 19 AM" src="https://user-images.githubusercontent.com/11865/86078848-96d1ae80-bac1-11ea-8d58-6b092b097ba7.png">

**Comment by opoudjis** [comment]
.... The fonts may or not be fontist; I know nothing whatsoever about it, and don't seek to.

I will work on this, but not mid-refactor. Prioritising for first ticket after refactor.

**Comment by opoudjis** [comment]
Font issue appears to have gone away, font is rendering fine as Baskerville under mn-samples-nist.

**Comment by opoudjis** [comment]
For Word, Figures etc tables of contents are broken too, although the normal table of contents is not.

**Comment by opoudjis** [comment]
Need to remove ",1" suffix in Word ToC directives.
