### ISSUE TITLE
Word: SP 800-90B review

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-nist#220]
Issue is originally posted in https://github.com/metanorma/mn-samples-nist/issues/50.

Differences between original and generated DOC outputs are listed below (continues #44).

1. Sections marked with `[preface]` attribute (i.e. Acknowledgements and Conformance Testing in this case) are on the same page as Abstract and Keywords in the original document. In generated DOC, they are places after Introduction section.

Original:
![image](https://user-images.githubusercontent.com/55683568/86540858-423a9300-bf08-11ea-8891-4613aca9f737.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/86540856-3058f000-bf08-11ea-8f66-6632a46f95f8.png)

2. Acknowledgements title is missing in the generated DOC, which can be seen in the image above.

3. Text should be justified. Difference can be seen in the image above.

4. ToC is placed before the Introduction section in the original, and after in the generated DOC.

5. ToC should include the Introduction section.

Original:
![image](https://user-images.githubusercontent.com/55683568/86542352-605ac000-bf15-11ea-9223-e4dd596201d7.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/86542348-5afd7580-bf15-11ea-8631-aa0d1b04b4d6.png)

6. ToC of the original document contains subsections at third level, e.g. section 2.2.1. Generated document contains sections and subsections up to the second level.

Original:
![image](https://user-images.githubusercontent.com/55683568/86542367-84b69c80-bf15-11ea-9d9c-e075fccedefa.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/86542373-8c764100-bf15-11ea-8b7e-dc844770eccd.png)

7. Pages are not numbered in the generated DOC, unlike in the original.

Original:
![image](https://user-images.githubusercontent.com/55683568/86540927-d1e04180-bf08-11ea-9d4a-8294e8f00b87.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/86540950-02c07680-bf09-11ea-8b6b-d1be34cb524b.png)

8. In the original document, ToC includes the title "List of Appendices" before appendices/annexes and it includes its subsections.

Original:
![image](https://user-images.githubusercontent.com/55683568/86540978-431ff480-bf09-11ea-9140-bc6d6e522a83.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/86540990-5e8aff80-bf09-11ea-91e4-ed6184c3badb.png)

9. Introduction and its subsections should be numbered.

Original:
![image](https://user-images.githubusercontent.com/55683568/86541007-837f7280-bf09-11ea-96b7-9cd00ad0d7a2.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/86541000-74002980-bf09-11ea-9759-28d979790550.png)

10. Symbols (formulae) in Symbols section are ordered differently.

Original:
![image](https://user-images.githubusercontent.com/55683568/86541012-9f831400-bf09-11ea-8c28-1b72a72e7092.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/86541011-9a25c980-bf09-11ea-977e-2bab32d832ef.png)

11. Description of symbols in glossary is written in the line below instead in the same line, which can be seen in the image above.

12. Hat symbol is placed too high in the generated document.

Original:
![image](https://user-images.githubusercontent.com/55683568/86541126-b5450900-bf0a-11ea-850d-eca18b59f5dc.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/86541115-a2cacf80-bf0a-11ea-908e-3bcff525203b.png)

13. In generated DOC, size of the brackets doesn't change regardless of arguments, which can be seen in the image above. Another example is shown below.

Original:
![image](https://user-images.githubusercontent.com/55683568/86541185-36040500-bf0b-11ea-893c-f2cd8c21bd12.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/86541184-2f758d80-bf0b-11ea-95bc-084b562cbbc8.png)

14. Titles of subsections in appendices/annexes are centered in the generated document, while left-aligned in the original.

Original:
![image](https://user-images.githubusercontent.com/55683568/86541090-57b0bc80-bf0a-11ea-95d3-6ca830b3d7be.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/86541087-52ec0880-bf0a-11ea-831b-a73eaf519b55.png)

15. Space under "text" in `stem` is ignored at the beginning and the end of the `text` argument.

Original:
![image](https://user-images.githubusercontent.com/55683568/86541269-c6dae080-bf0b-11ea-8a1e-d37ab5e7bd83.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/86541264-c04c6900-bf0b-11ea-9985-87321f67a903.png)

16. Reference for SP 800-90C is not fetched properly (fetching 800-90A or 800-90B). Below example shows a cross-reference which is generated the same as SP 800-90A.

Original:
![image](https://user-images.githubusercontent.com/55683568/86534131-2fa76600-bed6-11ea-8093-5567490576bd.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/86534137-3c2bbe80-bed6-11ea-92d5-6e7324e3b539.png)

17. `[class=steps]` attribute is not implemented in NIST, but I believe it would be useful, since in this document we have multiple pseudocodes which should use numbering style 1., 2., etc., since text sometimes refer to some specific step.
Current .adoc doesnt include this attribute, but if/when changes in NIST are made, .adoc should be changed accordingly.

Original:
![image](https://user-images.githubusercontent.com/55683568/86541333-4c5e9080-bf0c-11ea-8a56-ca781b2c14b0.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/86541343-61d3ba80-bf0c-11ea-8fd2-fa9d8dae99e1.png)

18. I think it's usual to write "small" sums in case they are added inline, i.e. sum limits are usually added next to the sum symbol, instead below and above it, in order to avoid changing line height.

Original:
![image](https://user-images.githubusercontent.com/55683568/86541386-c262f780-bf0c-11ea-9756-eeaddcba9891.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/86541391-c98a0580-bf0c-11ea-9638-15e195c4fd8a.png)

**Comment by opoudjis** [comment]
18 issues. Geez...

**Comment by opoudjis** [comment]
"1". Removing page break from preface clauses, acknowledgements.

Moved keywords up after abstract. Restored keywords to Word.

Page break at the end of boilerplate is not being moved out from between abstract and preface.

"2". Has already been fixed.

"4", "5", "9". Sections titled "Introduction" in NIST are not to be recognised as a preface section

**Comment by opoudjis** [comment]
"3". NIST documents have not been consistent in implementing justified text; I decline to do so in this instance.

"6". Three-level ToC done for all NIST SP documents. Fixing.

**Comment by opoudjis** [comment]
"7" Page numbers in the generated document are there, but are in the outer margins; in the original SP documents (other than the idiosyncratic SP 800 53, which has its own footer), they are centered. Updating footer.

**Comment by opoudjis** [comment]
"8". Appendixes appear in the normal ToC in SP 800 116r1, SP 800 126r3,  SP 800 53r4, and in a separate table only in this document. I decline to implement it.

**Comment by opoudjis** [comment]
"10": sorting of MathML terms in symbols is faulty, because space is being counted as a punctuation character: removing spaces from entries.

**Comment by opoudjis** [comment]
"14". Have conflated incorrectly centering of preface subtitles with left-align of annex subtitles.

**Comment by opoudjis** [comment]
"11". Glossary rendered as table

**Comment by opoudjis** [comment]
"12". OOXML rendering of `stem:[hat p]` is 

````
<m:limUpp><m:e><m:r><m:t>p</m:t></m:r></m:e><m:lim><m:r><m:t>^</m:t></m:r></m:lim></m:limUpp>
````

in rendered doc, and

````
<m:acc><m:accPr><m:ctrlPr></m:ctrlPr></m:accPr><m:e><m:r><i style='mso-bidi-font-style:normal'>p</i></m:r></m:e></m:acc>
````

in conversion of original

I'm seeing from the Microsoft XSLT that the reason for this is, it expects to see `<mover accent="true">` for accents, and AsciiMath is generating just `<mover>` Reporting to asciimath.

**Comment by opoudjis** [comment]
"13". Bracket size issues are longstanding, as reported in https://github.com/metanorma/metanorma-nist/issues/26. The fix for that was to enforce mfenced for brackets, but that is only done when the AsciiMath conversion is done with :msword option now. Fixing Html2Doc to trigger the Word-specific option.

**Comment by opoudjis** [comment]
"15". The source AsciiMath is

`stem:[p_i = ( text(number of) x_i text(in S))/L].`

Space is not interpolated between mtext and mathematical expressions, and indeed must not be: it would be impossible to generate text like _x^2^-the_ if we did. The solution is in markup: @anermina, I am changing the markup here to: 

`stem:[p_i = ( text(number of ) x_i text( in S))/L].`

As it turns out, Word is still trimming such strings (`normalize-space()`) when it converts them to OOXML. I am forcing mtext to retain boundary spaces by converting them to nbsp.

**Comment by opoudjis** [comment]
"16". Reported as https://github.com/relaton/relaton-nist/issues/42

**Comment by opoudjis** [comment]
"17". Agreed, this is a step. Adding.

**Comment by opoudjis** [comment]
"18". The generated OOXML is:

````
<m:oMath>
  <m:r><m:t>1&#x2212;</m:t></m:r><m:nary><m:naryPr><m:chr m:val="&#x2211;"></m:chr><m:limLoc m:val="undOvr"></m:limLoc><m:grow m:val="on"></m:grow><m:subHide m:val="off"></m:subHide><m:supHide m:val="off"></m:supHide></m:naryPr><m:sub><m:r><m:t>j=1</m:t></m:r></m:sub><m:sup><m:r><m:t>k&#x2212;1</m:t></m:r></m:sup><m:e><m:sSub><m:e><m:r><m:t>p</m:t></m:r></m:e><m:sub><m:r><m:t>j</m:t></m:r></m:sub></m:sSub></m:e></m:nary>
</m:oMath>
````

The source OOXML is:

````
<m:oMath>
<m:r>1-</m:r><m:nary><m:naryPr><m:chr m:val="∑"/><m:limLoc m:val="subSup"/><m:ctrlPr></m:ctrlPr></m:naryPr><m:sub><m:r>j</i></m:r><m:r>=1</m:r></m:sub><m:sup><m:r>k</m:r><m:r>-1</m:r></m:sup><m:e><m:sSub><m:sSubPr><m:ctrlPr></m:ctrlPr></m:sSubPr><m:e><m:r>p</m:r></m:e><m:sub><m:r>j</m:r></m:sub></m:sSub></m:e></m:nary></m:oMath>
````

The difference are `m:limloc val=undOvr` vs `subSup`, `m:grow, m:subHide, m:supHide`.

Omitting m:grow will make it small. BUT, as it turns out, m:grow is ALWAYS added in any limLoc generated from the OOXML XSLT: there is no assumption of inline sums in MathML. As for undOvr vs subSup, they are not differentiate in AsciiMath for sums.

So in order for me to generate small sums, I would need to postprocess sums and comparable expresssions like integers, if they are inline in text, to remove the m:grow.

**Comment by opoudjis** [comment]
"12": Asciimath have addressed the missing accents in MathML, but there is a new issue: AsciiMath is wrapping the accent character in mrow, but the Word XSLT is assuming that the accented character is present as an mo:

AsciiMath generates: `<mover accent="true"><mrow><mi>p</mi></mrow><mrow><mo>^</mo></mrow></mover>`
Word expects: `<mover accent="true"><mrow><mi>p</mi></mrow><mo>^</mo></mover>`

I'm going to do the normalisation myself as preprocessing.
