### ISSUE TITLE
PDF: SP 800-90B review

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-nist#221]
Originally posted in https://github.com/metanorma/mn-native-pdf-nist/issues/59.

> Differences between original and generated PDF outputs are listed below (continues https://github.com/metanorma/mn-samples-nist/issues/44).
> 
> * Acknowledgements and Conformance Testing (in this case, sections marked with [preface] attribute) should be on the same page as Abstract and Keywords (no need for page break).
> 
> Original:
> ![image](https://user-images.githubusercontent.com/55683568/86534033-a859f280-bed5-11ea-81fe-92f06b5c19c1.png)
> 
> Generated:
> ![image](https://user-images.githubusercontent.com/55683568/86534027-9f692100-bed5-11ea-8929-721d6c9f4063.png)
> 
> * Introduction section is completely missing in generated PDF.
> * Pseudocodes marked with `[pseudocode%unnumbered]` shouldn't be numbered (nor captioned as figure) in PDF.
> 
> Original:
> ![image](https://user-images.githubusercontent.com/55683568/86534267-75b0f980-bed7-11ea-8523-32f0d372f621.png)
> 
> Generated:
> ![image](https://user-images.githubusercontent.com/55683568/86534281-8b262380-bed7-11ea-9dd4-15971cdca729.png)
> 
> * Equations marked with `[stem%unnumbered]` shouldn't be numbered in PDF. They are also horizontally centered in the original document, unlike in PDF.
> 
> Original:
> ![image](https://user-images.githubusercontent.com/55683568/86534441-c2490480-bed8-11ea-9172-c6bf506d37e9.png)
> 
> Generated:
> ![image](https://user-images.githubusercontent.com/55683568/86534432-bcebba00-bed8-11ea-942f-3a911a9162a9.png)
> 
> * Square brackets and symbols are too close to each other in stem expressions in generated PDF. Some of the examples are shown below. Please note that `||` is not even recognizable in generated PDF.
> 
> Original:
> ![image](https://user-images.githubusercontent.com/55683568/86534328-d8a29080-bed7-11ea-9c9a-b5ea9c79c901.png)
> ![image](https://user-images.githubusercontent.com/55683568/86534361-2e773880-bed8-11ea-8c81-3dc9cc3495f0.png)
> ![image](https://user-images.githubusercontent.com/55683568/86534480-0e944480-bed9-11ea-8bb4-768f46f81151.png)
> ![image](https://user-images.githubusercontent.com/55683568/86534888-7ac47780-bedc-11ea-87ef-41685a198b72.png)
> ![image](https://user-images.githubusercontent.com/55683568/86535513-27085d00-bee1-11ea-9f40-377d7a0a2bea.png)
> 
> Generated:
> ![image](https://user-images.githubusercontent.com/55683568/86534323-d04a5580-bed7-11ea-81e7-1445ebf6c8b0.png)
> ![image](https://user-images.githubusercontent.com/55683568/86534356-20291c80-bed8-11ea-98e0-d6016a08e35d.png)
> ![image](https://user-images.githubusercontent.com/55683568/86534469-f7555700-bed8-11ea-859b-f886cb921d6d.png)
> ![image](https://user-images.githubusercontent.com/55683568/86534887-75ffc380-bedc-11ea-83f6-16a9095530fa.png)
> ![image](https://user-images.githubusercontent.com/55683568/86535504-15bf5080-bee1-11ea-8509-a636267f2dd2.png)
> 
> * Horizontal alignment (centering in this case) in tables is ignored in PDF.
> 
> Original:
> ![image](https://user-images.githubusercontent.com/55683568/86534707-b4947e80-beda-11ea-9afd-e40189e1ea87.png)
> 
> Generated:
> ![image](https://user-images.githubusercontent.com/55683568/86534708-bbbb8c80-beda-11ea-90f8-145ce387c8ea.png)
> 
> * Width and height of the sum symbol are adapted according to the sum limits or sum argument in PDF. However, this change is unconstrained, i.e. only one dimension is changing, making the sum symbol look stretched.
>   Examples can be seen on generanted pages 11, 34, 41, 45, 48, D-2, as shown below.
> 
> Original:
> ![image](https://user-images.githubusercontent.com/55683568/86534403-831ab380-bed8-11ea-81f0-22bee9ac213a.png)!
> ![image](https://user-images.githubusercontent.com/55683568/86534858-3507af00-bedc-11ea-9b59-62cbe7a6a4ec.png)
> ![image](https://user-images.githubusercontent.com/55683568/86535045-bf044780-bedd-11ea-9882-d7c1e6715278.png)
> ![image](https://user-images.githubusercontent.com/55683568/86535148-6ed9b500-bede-11ea-868a-0e555dbac4cf.png)
> ![image](https://user-images.githubusercontent.com/55683568/86535182-b3fde700-bede-11ea-857d-b54de5e27595.png)
> ![image](https://user-images.githubusercontent.com/55683568/86535767-04774380-bee3-11ea-9956-20686c0b8832.png)
> 
> Generated:
> ![image](https://user-images.githubusercontent.com/55683568/86534398-7ac27880-bed8-11ea-9427-90eac74375bf.png)
> ![image](https://user-images.githubusercontent.com/55683568/86534854-29b48380-bedc-11ea-9b72-2891f226c2d3.png)
> ![image](https://user-images.githubusercontent.com/55683568/86535038-b875d000-bedd-11ea-8fe7-e0f8ca192fcc.png)
> ![image](https://user-images.githubusercontent.com/55683568/86535143-697c6a80-bede-11ea-8c8f-b29d77b9d02b.png)
> ![image](https://user-images.githubusercontent.com/55683568/86535180-afd1c980-bede-11ea-976e-9e98ad8f353b.png)
> ![image](https://user-images.githubusercontent.com/55683568/86535757-fa554500-bee2-11ea-80e8-088cab3413f6.png)
> 
> * Examples are too indented in PDF, in comparison to the generated or original DOC.
> 
> Original:
> ![image](https://user-images.githubusercontent.com/55683568/86535787-2e306a80-bee3-11ea-8327-94cc7045b679.png)
> 
> Generated PDF:
> ![image](https://user-images.githubusercontent.com/55683568/86535781-283a8980-bee3-11ea-8cae-5051544b1365.png)
> 
> Generated DOC:
> ![image](https://user-images.githubusercontent.com/55683568/86535821-51f3b080-bee3-11ea-92d5-b14c68076ef9.png)
> 
> * Page numbers are centered in the original document.
> 
> Original:
> ![image](https://user-images.githubusercontent.com/55683568/86540927-d1e04180-bf08-11ea-9d4a-8294e8f00b87.png)
> 
> Generated:
> ![image](https://user-images.githubusercontent.com/55683568/86540925-c7be4300-bf08-11ea-8b9d-2adee156f432.png)

**Comment by opoudjis** [comment]
@anermina Taken the liberty of assigning this and the Word issue for work

**Comment by Intelligent2013** [comment]
Closing (original closed issue).
