### ISSUE TITLE
PDF: Line break in inline stem expression (SP 800-90B)

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-nist#226]
Originally posted in https://github.com/metanorma/mn-native-pdf-nist/issues/62.

> Is it possible to automatically insert a line break for an inline `stem` expression when margin is reached?
> 
> In NIST SP 800-90B, we have a very long argument for inline `stem`, which currently gets rendered like this:
> ![image](https://user-images.githubusercontent.com/55683568/89124944-172d6a00-d4db-11ea-968c-90564533f629.png)
> 
> Raw .adoc input is as follows:
> 
> ```
> Let stem:[S] be stem:[(2, 2, 3, 1, 3, 2, 3, 2, 1, 3, 1, 1, 2, 3, 1, 1, 2, 2, 2, 3, 3, 2, 3, 2, 3, 1, 2, 2, 3, 3, 2, 2, 2, 1, 3, 3, 3, 2, 3, 2, 1, 3, 2, 3, 1, 2, 2, 3, 1, 1, 3, 2, 3, 2, 3, 1, 2, 2, 3, 3, 2, 2, 2, 1, 3, 3, 3, 2, 3, 2, 1, 2, 2, 3, 3, 3, 2, 3, 2, 1, 2, 2, 2, 1, 3, 3, 3, 2, 3, 2, 1, 3, 2, 3, 1, 2, 2, 3, 1, 1, 3, 2, 3, 2, 3, 1, 2, 2, 3, 3, 2, 2, 2, 1, 3, 3, 3, 2, 3, 2, 1, 2, 2, 3, 3, 3, 2, 3, 2, 1, 2, 2, 2, 1, 3, 3, 3, 2, 3, 2, 1, 3, 2, 3, 1, 2, 2, 3, 1, 1, 3, 2, 3, 2, 3, 1, 2, 2, 3, 3, 2, 2, 2, 1, 3, 3, 3, 2, 3, 2, 1, 2, 2, 3, 3, 3, 2, 3, 2, 1, 2, 2, 2, 1, 3, 3, 3, 2, 3, 2, 1, 3, 2, 3, 1, 2, 2, 3, 1, 1)].
> ```

**Comment by Intelligent2013** [comment]
No, automatically it is not possible. Expression in PDF generates by jEuclid that doesn't have such feature.

**Comment by anermina** [comment]
Thank you for information, @Intelligent2013 . This question was originally posed in https://github.com/metanorma/mn-samples-nist/pull/49#discussion_r460669836 so I copied this information there. Closing this ticket.
