### ISSUE TITLE
NIST symbols as table

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-nist#230]
In NIST, `//terms` and `//dl[@type = "glossary"]` are rendered as a table. The same needs to be done for //definitions/dl, as found in https://github.com/metanorma/metanorma-nist/issues/220, with the `<dt>` in the left column and the `<dd>` in the right. Exemplified in mn-samples-nist, SP 800 90B.

**Comment by Intelligent2013** [comment]
Done.
![изображение](https://user-images.githubusercontent.com/5559926/91202677-d5bf6180-e70a-11ea-937e-c69e4897255e.png)
