### ISSUE TITLE
Add steps lists to NIST

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-nist#231]
ITU has `ol[@class = 'steps']`, with Arabic numbers rather than alphabetic entries. From https://github.com/metanorma/metanorma-nist/issues/220, this is to be added to NIST as well.

**Comment by Intelligent2013** [comment]
Done.
![изображение](https://user-images.githubusercontent.com/5559926/91328192-40d26c00-e7cf-11ea-82be-f5c635b05878.png)
