### ISSUE TITLE
PDF: Spacing in stem expressions

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-nist#233]
Space under "text" in `stem` is ignored at the beginning and the end of the `text` argument, or it seems to be ignored due to the smaller horizontal spacing than usual.

Original:
![image](https://user-images.githubusercontent.com/55683568/86541269-c6dae080-bf0b-11ea-8a1e-d37ab5e7bd83.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/86541264-c04c6900-bf0b-11ea-9985-87321f67a903.png)

This was solved in Word as written below (copied from https://github.com/metanorma/metanorma-nist/issues/220#issuecomment-680935982):
> As it turns out, Word is still trimming such strings (`normalize-space()`) when it converts them to OOXML. I am forcing mtext to retain boundary spaces by converting them to nbsp.

**Comment by Intelligent2013** [comment]
Done.
![изображение](https://user-images.githubusercontent.com/5559926/92406020-a3b4f300-f13f-11ea-9d7b-fd1f50b929ff.png)
