### ISSUE TITLE
Size of the brackets in equations, Word

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#26]
```adoc
s'_i = {(- 1, if s_i > s_(i + 1)),( + 1, if s_i <= s_(i + 1)):}
```

Gets rendered on AsciiMath.org correctly:
![screen shot 2019-01-08 at 6 54 59 am](https://user-images.githubusercontent.com/11865/50798177-623cc680-1312-11e9-9b14-bb22ad3b6c8e.png)

In Word, it shows as:
![screen shot 2019-01-08 at 6 55 40 am](https://user-images.githubusercontent.com/11865/50798182-6a950180-1312-11e9-8ad7-b0d30e7acb8f.png)

**Comment by opoudjis** [comment]
That is the output of the AsciiMath gem, already in MathML:

````
<mi>s</mi><msub><mi>'</mi><mi>i</mi></msub><mo>=</mo><mrow><mo>{</mo><mrow><mo>(</mo><mo>&#x2212;</mo><mn>1</mn><mi>,</mi><mo>if</mo><msub><mi>s</mi><mi>i</mi></msub><mo>&gt;</mo><msub><mi>s</mi><mrow><mi>i</mi><mo>+</mo><mn>1</mn></mrow></msub><mo>)</mo></mrow><mi>,</mi><mrow><mo>(</mo><mo>+</mo><mn>1</mn><mi>,</mi><mo>if</mo><msub><mi>s</mi><mi>i</mi></msub><mo>&#x2264;</mo><msub><mi>s</mi><mrow><mi>i</mi><mo>+</mo><mn>1</mn></mrow></msub><mo>)</mo></mrow></mrow>
````

That means that  this is an issue with asciimath not recognising the big bracket as a matrix: you can see the MathML just enumerates it as a horizontal list of expressions, in `mrow`, instead of using the required `mtable` tag.

**Comment by opoudjis** [comment]
This is another instance of asciidoctor asciimath's sensitivity to brackets: you need to wrap the cells of the matrix in `{: :}`:
````
stem:[s'_i = { ( {: - 1, :}, {: if s_i > s_(i + 1) :} ), ( {: + 1, :} , {: if s_i <= s_(i + 1 ) :} ):}]
````

I will not have time to fix these in the document, @ronaldtse: you  will have to do that.

In addition, the left brace is not resizing automatically to be as large as it needs to be. This is tied out somehow with the huge number of redundant spaces that are appearing in the OOMML-rendered formulas: if they are removed in the equation editor in linear mode, the brackets resize. But this will take extensive debugging.

This issue  will need to remain open.

**Comment by opoudjis** [comment]
same issue in ITU: 
[brackets_equations.zip](https://github.com/metanorma/metanorma-nist/files/3737118/brackets_equations.zip)

**Comment by opoudjis** [comment]
mfenced fixes the issue. Will submit Pull Request to asciimath.

**Comment by opoudjis** [comment]
Until the PR is approved in asciidoctor/asciimath, we will use our local copy at riboseinc/asciimath

**Comment by opoudjis** [comment]
asciidoctor/asciimath fix released.
