### ISSUE TITLE
Support stage "iterations"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#52]
https://csrc.nist.gov/CSRC/media/Publications/sp/800-57-part-2/rev-1/draft/documents/sp800-57pt2-r1-draft2.pdf

Look at the cover title.

<img width="861" alt="screen shot 2019-02-28 at 1 06 19 am" src="https://user-images.githubusercontent.com/11865/53508631-111ca800-3af5-11e9-831c-a114e9c12037.png">

Inner cover.

<img width="838" alt="screen shot 2019-02-28 at 1 06 33 am" src="https://user-images.githubusercontent.com/11865/53508653-1da10080-3af5-11e9-9c1b-6ba2066e9752.png">

First page.

<img width="806" alt="screen shot 2019-02-28 at 1 07 02 am" src="https://user-images.githubusercontent.com/11865/53508679-2bef1c80-3af5-11e9-93b9-81a38fccd0a3.png">

Header.

<img width="856" alt="screen shot 2019-02-28 at 1 07 17 am" src="https://user-images.githubusercontent.com/11865/53508689-33aec100-3af5-11e9-8fe4-c20f1764a39a.png">

**Comment by ronaldtse** [comment]
Also reflected in https://github.com/riboseinc/metanorma-model-nist

**Comment by opoudjis** [comment]
Incorporating into metadata field docnumber_long (the title above) the prefix DRAFT, if this is prepublication, and "(iteration)", if there is an iteration.

**Comment by ronaldtse** [comment]
Very nice, thank you!
