### ISSUE TITLE
Support "parts"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#53]
As reflected in https://github.com/riboseinc/metanorma-model-nist and https://csrc.nist.gov/CSRC/media/Publications/sp/800-57-part-2/rev-1/draft/documents/sp800-57pt2-r1-draft2.pdf

See #52 for screenshot details.

Example:

<img width="838" alt="screen shot 2019-02-28 at 1 06 33 am" src="https://user-images.githubusercontent.com/11865/53508788-6a84d700-3af5-11e9-812b-202dc3465c3f.png">

**Comment by opoudjis** [comment]
Already done as part of https://github.com/metanorma/metanorma-model-nist/issues/1

**Comment by ronaldtse** [comment]
@opoudjis sorry, in a newer ticket, NIST indicated “not” to support the Part concept. They said it was wrong to have Parts and it will never occur again.

**Comment by opoudjis** [comment]
Oh FFS.

**Comment by opoudjis** [comment]
Effaced all mention of part titles and part numbers.

**Comment by ronaldtse** [comment]
Thank you 🙇
