### ISSUE TITLE
Support "draft comment period"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#54]
The comment period isn't always given but when it is, it should be shown.

<img width="772" alt="screen shot 2019-02-28 at 1 10 00 am" src="https://user-images.githubusercontent.com/11865/53508869-94d69480-3af5-11e9-9514-9aff19719b7a.png">

(From: 
https://csrc.nist.gov/CSRC/media/Publications/sp/800-57-part-2/rev-1/draft/documents/sp800-57pt2-r1-draft2.pdf)

**Comment by opoudjis** [comment]
Do we need to put in the extension to comment periods? If so, we need to put in an extra date in the comment period, of when it was last extended. @ronaldtse, please confirm this is a requirement.

**Comment by ronaldtse** [comment]
Hmmm... 

It was said:
> In draft stages, there is a “Comment Period” that contains “from” and “to” dates.
> The “to” date is optional. There are some instances where a comment period is open-ended. Occasionally, we will extend the “to” date if we need to give commenters more time to respond.

I suppose that we should have that.

**Comment by opoudjis** [comment]
Added commentperiod/extended to allow for the extra date.

**Comment by ronaldtse** [comment]
Thanks!
