### ISSUE TITLE
MathJax script in HTML differs from recommended JS

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#57]
User report (on Windows):

> The generated HTML specifies:
> `<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=AM_HTMLorMML"></script>`
> But the math script is not rendered correctly when I opened the local file in Chrome

(I can see math properly rendered on Mac Safari and Chrome)

> MathJax site says to use:
> `<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>`
> When I replace the script in the HTML with the MathJax site script, the math *appears* to render correctly, from what I can see.

Maybe it's a Windows thing?

We should probably:
1. Update MathJax to the newer version.
2. Use the MathJax recommended tag to load it.

**Comment by opoudjis** [comment]
I've moved it to the latest version and latest.js alias, as recommended. Someone else will need to test it on Windows, but I've complied with request.

**Comment by opoudjis** [comment]
Fixed in isodoc.
