### ISSUE TITLE
HTML: on Windows Chrome, graphics are not displaying

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#60]
> Graphics are not displaying (NIST Logo, DoC seal), and appear to be encoded inline. E.g., For the NIST logo, it appears to have been embedded (base64) in the HTML, instead of linking to a separate file.
> (Code is:  `<div class="logo-wrapper"> <img id="NIST-logo" src="data:image/png;base64,… `)

That’s very strange — they show up correctly for me. I wonder if there is a permission issue with Windows Chrome?

There are two reasons why we switched to use inline data:
1. The ability to have a single XML file fully represent a standard document
2. On many platforms, "local file loads" are prohibited from the browser.

**Comment by opoudjis** [comment]
There is an option not to use data-uri encoding, and if they would rather enable that option for NIST, they can do so.

Debugging the behaviour of data-uri images with Chrome is something that should be passed on to Pierre.

... I don't believe there is anything else for me to say here.

**Comment by ronaldtse** [comment]
@opoudjis this problem may have been solved in the newer version. The user was using metanorma 1.1.3 via Chocolatey, the latest 1.1.4 has been released yesterday.

Let's keep this "on-hold" (as it currently is) right now.

**Comment by opoudjis** [comment]
@ronaldtse Update on this?

**Comment by opoudjis** [comment]
This needs to be looked at by someone with Windows access; and I do not know what the initial document was that prompted this ticket.

**Comment by ronaldtse** [comment]
Assigning to @CAMOBAP795 in case he has Windows access to try... Thanks!

**Comment by CAMOBAP795** [comment]
Works for me on Windows 10 for both Chrome & Edge browsers:

![](https://user-images.githubusercontent.com/2169738/78671006-5231df00-78e7-11ea-8e9a-9028b44e811b.png)
![](https://user-images.githubusercontent.com/2169738/78671014-54943900-78e7-11ea-8f21-44a26fbe8d3c.png)

**Comment by ronaldtse** [comment]
LGTM, let's close this!
