### ISSUE TITLE
HTML: Title styling and issues

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#61]
> 1. make line spacing more compact
> 2. Remove "National Institute of Standards and Technology" Year  and "Information Security" from right after title.

**Comment by opoudjis** [comment]
Remove "National Institute of Standards and Technology" Year: done in #62

**Comment by opoudjis** [comment]
Removed first of two instances of subseries.

Reduced .coverpage-doc-identity line-height to 1.5em from 2em; font-size remains 2em
