### ISSUE TITLE
HTML: Authors -- Include blank line after author grouping

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#63]
Authors -- Include blank line after author grouping.

**Comment by opoudjis** [comment]
There already is a blank line: please clarify what you want here.

<img width="795" alt="image" src="https://user-images.githubusercontent.com/1911039/54647192-bd9aea00-4af5-11e9-9908-94da64953001.png">

**Comment by ronaldtse** [comment]
I think in between “author groups” there should be a blank line.
