### ISSUE TITLE
Make ToC depth adjustable in document attributes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#64]
User request:

> Will it be possible to adjust the maximum ToC depth displayed? Some of our pubs currently go down to 5 levels in the ToC (which is way too deep IMO) and may be excessive for this display.
> Current display in the generated HTML file appears to be 2 levels, but we may want to display 3 or 4, depending on the document.

So we will want to make ToC depth a configurable option.

**Comment by opoudjis** [comment]
I'm going to separate the maximum depth for HTML and for Word, because the HTML navigation panel is much narrower.

**Comment by ronaldtse** [comment]
Sounds good. So this introduces “per output format options”. May want to document it.

**Comment by opoudjis** [comment]
Everything gets documented, although I don't know that this warrants more than a mention among document attributes.

**Comment by ronaldtse** [comment]
Maybe there should be a section on "ToC"?

**Comment by opoudjis** [comment]
Making these options in isodoc, so they can apply to all gems.

**Comment by opoudjis** [comment]
I will have to parameterise the ToC javascript for HTML output, because https://github.com/metanorma/isodoc/issues/79 has been on hold since November.

**Comment by opoudjis** [comment]
> Maybe there should be a section on "ToC"?

https://github.com/metanorma/metanorma.com/issues/72. And I am in no hurry to do that, given what you keep throwing at me.
