### ISSUE TITLE
"Standard" vs "Published" under cover page

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#65]
See image:

<img width="643" alt="Screen Shot 2019-03-17 at 2 08 37 PM" src="https://user-images.githubusercontent.com/11865/54486094-3283df00-48be-11e9-8143-2f72dd60433d.png">

>  What are "Standard" and "Published" right below Walter Copan's name and title? Remove "Standard". If Published is indicative of "Final" then we have to rethink where to put this.
> If a document is a Draft, then we need to indicate this at the very top of the HTML (and PDF and DOC) where "NIST SP 800-116" is displayed. I see were this value is stored in the XML, but not in the .adoc file.

**Comment by opoudjis** [comment]
"Standard" is the document type.

"PUBLISHED" is the document status, which will now be replaced by "FINAL".

To indicate document status in a different place depending on whether it is a draft or not is an unnecessary inconsistency, but I can suppress display of status if the document is FINAL.

Those are document attributes in the .adoc file; it's just that docstatus has a default value of "final", if not supplied.

**Comment by opoudjis** [comment]
@ronaldtse Need feedback on this.

**Comment by ronaldtse** [comment]
I thought I replied but apparently didn't post... apologies.

There's no "Standard" document type in NIST, they only have publication "series". Their "series" is the "document type". We need to update our modeling. 

<img width="109" alt="Screen Shot 2019-03-27 at 9 48 57 AM" src="https://user-images.githubusercontent.com/11865/55044504-8be5ce00-5075-11e9-8703-2cea8e874828.png">

That's why we are asked to remove "Standard".

**Comment by opoudjis** [comment]
If we cannot call SP 800 a series because NIST don't call it a series, I don't see why we should call what they do call a series a doctype. Doesn't this just mean we ignore doctype completely, since that information is encoded as the series?

**Comment by ronaldtse** [comment]
Well... let's put it this way. NIST publishes many things. Each publication series, such as "SP" ("Special Publications") is one. SP 800 is technically a "sub"-whatever.

For example, NIST AMS ("Advanced Manufacturing Series") is a separate "Series".

In ISO, we have "Standard", "TS" ("Technical Specification"), they share the same numbering space. "Guide" is separate because they don't share the numbering space. But all of these we model as "doctype"s.

Given in Metanorma we do not have a native model for "Series", calling "SP" a doc-type valid. "SP 800-53" can be modeled with the doctype "SP" and number "800-53".

**Comment by opoudjis** [comment]
We decidedly do have a native model for Series, we just happen not to have used it to date. Removing series from bibdata, putting series value into doctype instead.

**Comment by ronaldtse** [comment]
Agreed. I don't know if there are other `doctype`s -- but this maybe the best.

For example:
* SP 800-53 uses a different layout/structure.
* SP 800-30 / 800-37 uses a different layout.

So the `doctype` could be different for those.

**Comment by opoudjis** [comment]
Removed "Standard", i.e. doctype from title page. Have already added prefix "DRAFT" for all non-final documents before the top line document identifier (`docidentifier_long`).

**Comment by opoudjis** [comment]
Does this mean no indication on the front page of the distinction between public-draft, retired-draft, private-draft, withdrawn?

**Comment by opoudjis** [comment]
Deferred status indication to #79
