### ISSUE TITLE
HTML: “Authority” statement need to hyperlink the DOI

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#68]
> “Authority” statement:  need to hyperlink the DOI.

(See image, the DOI link is not hyperlinked)

<img width="807" alt="Screen Shot 2019-03-17 at 2 12 47 PM" src="https://user-images.githubusercontent.com/11865/54486137-bfc73380-48be-11e9-9c94-dbbdf14976cf.png">

**Comment by opoudjis** [comment]
Done as part of #76
