### ISSUE TITLE
Backwards compatibility necessary for order of "References" in appendixes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#71]
> When the References appendix was converted to the Bibliography section, it caused the Appendices following it to bet re-labeled (appendix letters don't match what's in the PDF). 
> This is what we are moving towards in our pubs, but if we want to convert existing pubs--such as 116 Rev. 1--that include the References as an Appendix, do you suggest that we just not use the [[bibliography]] tag, to prevent its being moved?

I suspect we can make an exception option that retains the order of the References section in the appendix?

* We turn on this option for old documents so the bibliography can be placed wherever according to where it has been placed.
* Omit this option for new documents so that the bibliography is always the first appendix.

**Comment by opoudjis** [comment]
Created `:biblio-as-appendix:` document attribute to request legacy behaviour.
