### ISSUE TITLE
HTML: Appearance of Terminology section needs improvement

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#72]
In 800-116, Appendix F Terminology is shown as this screenshot.

<img width="820" alt="Screen Shot 2019-03-17 at 2 30 25 PM" src="https://user-images.githubusercontent.com/11865/54486295-36653080-48c1-11e9-9824-51ea7dedbb0a.png">

> Is it possible to limit the Term column width to 1/3 of the page, and turn on Word Wrap?

The key of the suggestion is that the current layout does not provide best use of space. It's either a better table (i.e. terms 1/3, 2/3 defs), or something like ISO's.

Let me find out.

**Comment by opoudjis** [comment]
Do report back; setting cell width in Word is not a great idea given auto-width.

**Comment by opoudjis** [comment]
Cannot replicate: this is what I'm getting, without intervening in the table size at all:

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/1911039/54995380-b5bdd700-501a-11e9-83b5-f0ac5ef4c7f8.png">

**Comment by ronaldtse** [comment]
How about in HTML? This ticket is about HTML...

**Comment by opoudjis** [comment]
I did not realise that. HTML is much more straightforward to control.

**Comment by opoudjis** [comment]
The request to turn on Word Wrap does not make any sense, and I will ignore it.

**Comment by opoudjis** [comment]
Replaced `grid-template-columns: max-content auto`, which is auto-size (and is not wrapping the left column lines) with `grid-template-columns: 25% 75%`, which is brute force.

**Comment by ronaldtse** [comment]
Hope it works...
