### ISSUE TITLE
XML: NIST should not be considered as an author

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#74]
> NIST should not be listed as an author (see first <contributor> instance)

Well said.

**Comment by opoudjis** [comment]
Does this mean no corporate author at all, just individual authors?

**Comment by ronaldtse** [comment]
The affiliation of authors is set separately. Maybe NIST should be listed as a publisher? Or a copyright holder? Let me find out.

**Comment by opoudjis** [comment]
NIST is already listed in the templates as both publisher and copyright holder.

**Comment by ronaldtse** [comment]
In the XML? This ticket is only about XML.

**Comment by opoudjis** [comment]
Yes, in the XML.
