### ISSUE TITLE
Authorship: separate contribution affiliation and affiliation location

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#75]
> For contributor affiliations, we should separate the organization name from the organization location (location is an OPTIONAL field).

This means we just need to split the contributor location into a separate document attribute.

**Comment by opoudjis** [comment]
Will use `:address:` field which already exists in Metanorma. So:

````
:fullname_2: Ketan Mehta
:affiliation_2: Computer Security Division, Information Technology Laboratory
:fullname_3: Nabil Ghadiali
:affiliation_3: National Gallery of Art
:address_3: Washington, DC
```

**Comment by ronaldtse** [comment]
This works. Thanks!

**Comment by ronaldtse** [comment]
Maybe it's time to think about an address solution across Metanorma flavors, but it's very hard to represent things in AsciiDoc attributes.

**Comment by opoudjis** [comment]
This solution is already in place in Metanorma, and I am implementing the fix to add the address in isodoc. The only thing that would need to be added to Metanorma is a breakdown of addresses into components, which I would argue is pointless anyway.
