### ISSUE TITLE
Display of statuses

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-nist#79]
Spawned from #65 

NIST uncomfortable with explicit display of status: would prefer DRAFT prefix to top line of document for public drafts, nothing for final documents.

We think other statuses, retired-draft, private-draft, withdrawn, should still be indicated explicitly on the title page.

**Comment by ronaldtse** [comment]
<img width="216" alt="Screen Shot 2019-03-27 at 7 45 40 PM" src="https://user-images.githubusercontent.com/11865/55073530-e78d7700-50c8-11e9-9dbb-6f9f5f6a81e8.png">

For each of these statuses:

* `private-draft` : should we display a "private draft warning"?
* `public-draft` : should display "DRAFT" warning and also provide "public comment" section
* `final` : published, nothing to show
* `retired-draft` : should display warning that the draft is "Retired". (Example: https://csrc.nist.gov/CSRC/media/Publications/sp/800-26/rev-1/archive/2005-08-15/documents/sp800-26r1-draft.pdf)
* `withdrawn` : should display warning that document is withdrawn. (Example: http://dx.doi.org/10.6028/NIST.SP.800-53r3)

**Comment by opoudjis** [comment]
Please do the following:

* Get me Word samples of these, because I will not spend a week trying to recreate these in Word HTML.
* Get Pierre to mock up HTML equivalents.
* Make up your mind well in advance as to whether you want these treated as boilerplate or as dynamic text. Lamentably, this seems to be a  mixture of both.

This is going to be a proliferation of logic and templates, and NIST had better be prepared to support this going forward.

**Comment by opoudjis** [comment]
> Line numbers are shown 

LINE NUMBERS?!

**Comment by ronaldtse** [comment]
The Word templates have been uploaded to `mn-nist-documents/references/`

**Comment by ronaldtse** [comment]
Clarification:

Retired Draft: Cancelled document, not superseded
Withdrawn Public Draft: Superseded draft by another public draft
Withdrawn Final Publications: Superseded document

**Comment by opoudjis** [comment]
NIST SP 800-37r1 (https://doi.org/10.6028/NIST.SP.800-37r1)

I will need to Doc source from you.

**Comment by ronaldtse** [comment]
For the record the "to be withdrawn" cover page is shown here.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/11865/55451621-4d688a00-5606-11e9-8b8c-9c1a96038d97.png">

I strongly prefer they use the same cover page style for all inactive states...

**Comment by opoudjis** [comment]
Line numbers implemented for public drafts: #81

**Comment by ronaldtse** [comment]
This issue is still useful for the describing for elements in drafts, but for the cover pages, they are superseded by #90 and #91.

**Comment by opoudjis** [comment]
The only non-cover page information in this ticket is the list of Public Draft features:

> The word "DRAFT" is rendered in the cover page, the inner cover page and the page header of content pages.
> Line numbers are shown.
> Under "Authority", there is a section to show contact information for draft comments.
> There is sometimes a page for "Call for patent claims".

As these have all been implemented, this ticket is closed.
