### ISSUE TITLE
Line numbers possible?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#81]
In NIST public drafts, line numbers are shown:

We may be able to implement them:

* Word: https://www.datanumen.com/blogs/6-handy-tips-add-line-numbers-set-formatting-word-document/
** Hopefully supported by MHT

* HTML: https://www.sylvaindurand.org/using-css-to-add-line-numbering/

Originally from #79 .

**Comment by opoudjis** [comment]
Yes, it is supported in Word HTML CSS:

````
@page WordSection1 {
mso-line-numbers-count-by:1;
mso-line-numbers-restart:continuous;
}
````

Will try to treat Word stylesheet as a liquid template, to add those rules conditionally.

**Comment by opoudjis** [comment]
Given that the HTML document does not has fixed width, the request to put line numbers in HTML is impossible. Please tell them not to ask for it in HTML. The CSS you have linked to for HTML requires violent intervention in the HTML source (wrapping each line in an element), and is not even feasible.

**Comment by ronaldtse** [comment]
Thanks for the Word one!

You're right regarding the fixed width issue on HTML, let's consider this complete now. There are no line numbers in HTML.

(Until one day it is determined the HTML document must follow the Word's line breaking/numbering...)

**Comment by ronaldtse** [comment]
Oops it's not yet done, reopening.

**Comment by opoudjis** [comment]
Implemented.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
