### ISSUE TITLE
Windows tests broken

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-nist#83]
Tests broken after https://github.com/metanorma/metanorma-nist/commit/60ce83d00e9f4b801bd778bf71fb81010831bcd2

**Comment by opoudjis** [comment]
If travis also breaks, ignore it. All metanorma-* gems are dependent on isodoc and metanorma-standoc, and any mods to them (especially refactoring) is going to break things until they are all released in tandem. This breakage is because of such a refactoring in isodoc.

**Comment by CAMOBAP795** [comment]
Closing because the same test failed on travis
