### ISSUE TITLE
Distinct withdrawn and obsoletes relations

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-nist#84]
Obsolete means that the previous one is withdrawn. Supersedes does not necessarily entail that meaning.

They have “to be withdrawn” standards, meaning that it has been superseded but remain active until some future date.

**Comment by opoudjis** [comment]
I am presuming that "to be withdrawn" will have a coverpage like in #79; does that mean that "to-be-withdrawn" is a distinct status? If not, and the document remains "final", NIST will need to tell me if they want the superseding document identifier displayed anywhere.

**Comment by ronaldtse** [comment]
NIST SP 800-37r1 (https://doi.org/10.6028/NIST.SP.800-37r1)

It's a practice that they have only started using before the shutdown, and this is the first and only example for now.

If a future "withdrawal" date is given then we know it is "to-be-withdrawn". It is a "distinct status", but the status comes from inferring from its bib-dates. i.e. before the date it is "active", after the date it is "withdrawn".
