### ISSUE TITLE
Implement representations of a NIST publication document identifier

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#88]
In Metanorma we have three ways of referring to a document.

## 1 "Full-form" reference

(now #98) 

## 2 “Abbreviated form” reference

This form is used in the Authority section.

``` 
Natl. Inst. Stand. Technol. {abbrev(series)} {docnumber} {part | abbrev(volume)}, {abbrev(revision)}
```
* `abbrev(series)` represent the abbreviation of the Series title
* (Note: there is no `{update-date}`)
* Abbreviate “Revision” to “Rev.” and “Volume” to “Vol.”

<img width="480" alt="image" src="https://user-images.githubusercontent.com/11865/55641177-da2a6800-57ff-11e9-883e-40999631e485.png">

Examples:
* "Natl. Inst. Stand. Technol. Spec. Publ. 800-78-4"
* "Natl. Inst. Stand. Technol. Spec. Publ. 800-116”
* "Natl. Inst. Stand. Technol. Spec. Publ. 800-57 Part 1, Revision 4”
 
## 3 "Short form" reference

The “short form” is used to cite the documents within text. 

It is used in these situations:

1. Locality references. “In Section 3.2 of SP 800-187…” (the "SP 800-187” is a link). In ISO it is “In Clause 3.2 of ISO 9001…”. (Or we do “In Section 3.2 of [SP 800-187]…”, as in current NIST pubs)

(Notice NIST pubs are composed of "Sections" not "Clauses")

In Metanorma we can specify this as “In \<<SP800-187,section=3.2>>…” or just “In \<<SP800-187,3.2>>”
 
2. A generic document reference. “SP 800-53 describes…”. In ISO also “ISO 9001 describes …”.

This form does not specify a revision or update date.

In Metanorma we specify this as “\<\<SP800-53>> describes…”.

3. “All parts”. “The SP 800-57 subseries describes key management…”. In ISO “The ISO 8601 (all parts) standards…”.
 
In Metanorma we specify this as “\<\<SP800-57>> describes key management …”, and have a reference labelled like this:
 
```
* [[[SP800-57,NIST SP 800-57 (all parts)]]]
```

"NISTIR 6885 2003 Edition (February 2003)” is a poor indicator.

The correct rule should be:

* SP:
```
NIST {abbrev(series)} {docnumber } {edition, optional}
```

* FIPS:
```
FIPS {docnumber }
```
(`docnumber` is the full FIPS number, including revision, e.g., `140-2`.)

## 4 Machine-readable form

The machine-readable form is:
```
NIST.{series}.{docnumber}.{part|volume}.{revision}.{update-date}
```

Generally, this rule should be able to uniquely identify an edition of a document.
 
Where:
```
series = SP, IR, FIPS, TN [“Technical Note”], HB [“Handbook”], CSWP [“Cybersecurity White Paper”] 
```
 
Details:
* Various scenarios for “part”:
  * “Part 1” use “pt1”;
  * When a letter part is indicated, “800-63A” we should keep it as part of the docnumber (i.e., don’t indicate “pt”)
* Volumes: use “v1”
* Revision typically: “Revision 1” use “r1”
* If a superseding edition is a full revision, it will get the next Rev. #.
If a superseding edition is just an errata update, we can use the update date from the title page (“includes updates as of…”) to uniquely identify this edition. Preferably use -yyyymmdd format
 
Some examples:
* NIST.SP.800-53r4-20152201       supersedes              NIST.SP.800-53r4-20140115
* NIST.SP.800-63A-20171201        supersedes              NIST.SP.800-63A
* NIST.SP.800-57pt1r4                    supersedes              NIST.SP.800-57pt1r3
* NIST.SP.800-160v1                       supersedes              NIST.SP.800-160-20180103 
* Undated form "NIST.SP.800-53r4"

**Comment by opoudjis** [comment]
This profusion of identifiers is an indulgence, and NIST need to be told that it is an indulgence. There is a lot that they have simply done wrong.

I already have a routine that generates the "Abbreviated form" and the "Full Form" from the Short Form. I am treating the Short Form as the source.

From discussion: the Machine Readable forms are not sources of truth, and only relate to the current document (since that is the only document for which the required fields are known from document metadata). It may be used eventually to generate DOIs. For now, it will be a variant docidentifier, generated for interest: it is not a source of truth of anything. (Which means "NIST.SP.800-53r4-20152201 supersedes NIST.SP.800-53r4-20140115" is not going to be how relaton does anything: it will continue to rely on NistBib, and that likely means that drafts won't be retrieved.)

**Comment by opoudjis** [comment]
The short form still needs to provide revision date, which is not included in the doc identifier. Propose "(Month YYYY)" or "(YYYY-MM-DD)" following doc identifier: that appears to be what they actually use.

**Comment by opoudjis** [comment]
So, for short form as input into NistBib (which allows the NIST prefix):

* NIST SP 800-53r4 (20152201) supersedes NIST SP 800-53r4 (20140115)
* NIST SP 800 63A (December 2017) supersedes NIST SP 800-63A
* NIST.SP 800 57 Part 1 Revision 4 supersedes NIST SP 800-57 Part 1 Revision 3 ("Rev." is also accepted, and converted to "Revision")
* NIST.SP 800 160 Volume 1 supersedes NIST SP 800-160 (20180103) ("Vol." is also accepted, and converted to "Volume")
* Undated form "NIST SP 800 53r4"

**Comment by opoudjis** [comment]
* Citations use Month YYYY
* Relaton uses YYYY-MM

**Comment by opoudjis** [comment]
> "NISTIR 6885 2003 Edition (February 2003)” is a poor indicator.

This would be handled as follows:

* Short form in displayed citation: `NISTIR 6885 (February 2003)` (there is no edition or revision number to use, so it has to be the date)
* Form user enters in Asciidoctor: `NISTIR 6885 (February 2003)` or `NISTIR 6885 (2003-02)` (which means NISTBib has to be able to parse dates)
* Canonical identifier, if there is such a thing: `NISTIR 6884 (2003-02)`.

**Comment by opoudjis** [comment]
The "Full Reference" stuff is not about document identifiers at all. It is about rendering a reference based on a full relaton record. And the irresponsible idiosyncrasy about FIPS means that this is an exception-ridden mess based on a full relaton record. It will draw on the preliminary work done  in https://github.com/metanorma/iso690render

**Comment by opoudjis** [comment]
At your suggestion, @ronaldtse, I have already withdrawn support for Part:  https://github.com/metanorma/metanorma-nist/issues/53. I will not support Part unless you expressly tell me to.

**Comment by opoudjis** [comment]
Added `:volume:` to information model, as attribute of identifier.

**Comment by opoudjis** [comment]
# 2 “Abbreviated form” reference

> Abbreviate “Revision” to “Rev.” and “Volume” to “Vol.”

Your sample does not show the abbreviation of “Revision” to “Rev.”

Doing replacement of "Volume" with "Vol." inline in template. "Volume" and "Revision" are embedded in the document identifier.

**Comment by opoudjis** [comment]
## 3 "Short form" reference

I am ignoring "all parts" because of #53 

I will strip Volume and Revision from the citation display of references, *only* if the volume and revision are unique for each document number.

**Comment by opoudjis** [comment]
"Machine Readable" identifier generated as `docidentifier[@type = "nist-mr"]`

**Comment by ronaldtse** [comment]
> I am ignoring "all parts" because of #53

Agree. That was a bad example.

> I will strip Revision and Date from the citation display of references, only if the Revision and Date are unique for each document number.'
> These are identified as "Rev. ...", "Revision ...." and " (Month YYYY)", whichever comes first.

What does this mean? I understand about Editions, but why do we need to strip Revision?

> The prefix NIST is stripped from all cross-references, as required here.

Sorry... Notice that the actual "rule" states the following. My examples were bad -- the rule is right (the rules were the conclusion of the examples).

NIST:
```
NIST {abbrev(series)} {docnumber } {edition, optional}
```

FIPS:
```
FIPS {docnumber }
```

**Comment by opoudjis** [comment]
>> I will strip Revision and Date from the citation display of references, only if the Revision and Date are unique for each document number.'
>>These are identified as "Rev. ...", "Revision ...." and " (Month YYYY)", whichever comes first.

> What does this mean? I understand about Editions, but why do we need to strip Revision?

Because you asked for it:

> A generic document reference. “SP 800-53 describes…”. In ISO also “ISO 9001 describes …”.
> This form does not specify a revision or update date.

Which means that if it's SP 800-53 Revision 1, you have just asked for it to be cited as SP 800-53. (If on the other hand the revision is integrated into the document number, as in SP 800-53r1, I am not going to detected it and remove it.)

>> The prefix NIST is stripped from all cross-references, as required here.

> Sorry... Notice that the actual "rule" states the following. My examples were bad -- the rule is right (the rules were the conclusion of the examples).

You are not being clear. So NIST SP 800-53 is cited not as "SP 800-53", as your examples have, but as "NIST SP 800-53"?

In that case, your prefix NIST is misleading anyway: the series abbreviations as I have recorded them already include the NIST prefix most of the time.

````
      SERIES_ABBR = {
        "nist-ams": "NIST AMS",
        "building-science": "NIST Building Science Series",
        "nist-fips": "NIST FIPS",
        "nist-gcr": "NISTGCR",
        "nist-hb": "NIST HB",
        "itl-bulletin": "ITL Bulletin",
        "jpcrd": "JPCRD",
        "nist-jres": "NIST JRES",
        "letter-circular": "NIST Letter Circular",
        "nist-monograph": "NIST MN",
        "nist-ncstar": "NIST NCSTAR",
        "nist-nsrds": "NIST NSRDS",
        "nistir": "NISTIR",
        "product-standards": "NIST Product Standards",
        "nist-sp": "NIST SP",
        "nist-tn": "NIST TN",
        "other": "NIST Other",
        "csrc-white-paper": "CSRC White Paper",
        "csrc-book": "CSRC Book",
        "csrc-use-case": "CSRC Use Case",
        "csrc-building-block": "CSRC Building Block",
      }.freeze
````

Kindly confirm, so I can close this ticket.

**Comment by opoudjis** [comment]
>>> The prefix NIST is stripped from all cross-references, as required here.
>> Sorry... Notice that the actual "rule" states the following. My examples were bad -- the rule is right (the rules were the conclusion of the examples).
> You are not being clear. So NIST SP 800-53 is cited not as "SP 800-53", as your examples have, but as "NIST SP 800-53"?

Per the template examples, NIST is indeed stripped from reference citations.

**Comment by ronaldtse** [comment]
> (On stripping Revision) Because you asked for it:
This is a misunderstanding. As mentioned, "SP 800-53 describes..." was a poor example; it should have been "SP 800-53 Rev. 4"

Let's state the full rule for Short Reference:

**Comment by opoudjis** [comment]
Undone stripping of revisions and Month-Year in citations. Maintaining stripping of NIST in citations.
