### ISSUE TITLE
Migrate NIST publication template into a Metanorma template

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#89]
The Metanorma template repository for NIST is at GitLab `metanorma/mn-templates-nist`.

This task is to migrate the NIST publication template (in GitLab `metanorma/mn-nist-documents`) to a Metanorma AsciiDoc template. This includes all the guidance text, instructions, comments, etc.

**Comment by opoudjis** [comment]
Will not action until https://github.com/metanorma/metanorma/issues/45 closed.

**Comment by opoudjis** [comment]
Giving up on waiting on https://github.com/metanorma/metanorma/issues/45

**Comment by opoudjis** [comment]
I am not looking at the files I'm porting across from the OGC metanorma directory too closely, and I'm not going to test this particularly. I'm populating the content of the template. Someone else is going to have to operationalise this.

**Comment by opoudjis** [comment]
The OGC structure for templates is baroque. There is no way I'm replicating that for NIST. My God.

Whatever I'm going to come up with is going to be much, much simpler.

**Comment by opoudjis** [comment]
mn-templates-ogc/standard/requirements/requirement.adoc

`[requirement,type="general",id="/req/req-class-a/req-name-1",obligation="shall"]`

I am fixing this in OGC. RTFM, @ronaldtse:

> `obligation`:: Can contain one or more of "requirement", "permission", "recommendation",
comma-delimited. Using this attribute will override the obligation of the blog.

**Comment by ronaldtse** [comment]
@opoudjis the templates are already fully operational in https://github.com/metanorma/metanorma-cli/pull/35 .

**Comment by opoudjis** [comment]
... And I'm still fixing them in mn-templates-ogc. Is your comment about the gem release?

**Comment by ronaldtse** [comment]
Ah you're fixing the OGC template. OK. The point is, these are from https://github.com/opengeospatial/templates , we just need to make them compilable in Metanorma.

The metanorma-iso templates already work properly.

**Comment by opoudjis** [comment]
I have already realised that OGC is a pessimal place to take templates from. I'll use CSD or ISO instead.

**Comment by ronaldtse** [comment]
> The OGC structure for templates is baroque. There is no way I'm replicating that for NIST. My God. Keeping track of an images directory as distinct from a figures directory? That's meant to make things easier for people?!

Please, don't change this. This is directly from https://github.com/opengeospatial/templates . If you want people to take control of their stuff, you ought to let them to do what they want.

**Comment by ronaldtse** [comment]
CSD is also operational (I tested it). I'm thinking that we need to make tests to ensure the templates run. I will post.

**Comment by ronaldtse** [comment]
(NIST templates will be placed in GitLab)

**Comment by opoudjis** [comment]
> Please, don't change this. 

I'm not changing it, I'm saying it does not make things easier for users; but clearly it aligns with OGC practice. I will use ISO as the template source.

Yes, I am putting the NIST template into GitLab. Please delete the github instance, it's confusing.

I will not maintain the templates or author testing for them. This is part of my ongoing work to constrain my involvement to something manageable; and the fiddliness of shell scripts is not something I am comfortable dealing with. Please find another dev for that.

**Comment by ronaldtse** [comment]
> Yes, I am putting the NIST template into GitLab. Please delete the github instance, it's confusing.

Thanks. I'm hoping we can move to GitHub one day though.

> I will not maintain the templates or author testing for them. This is part of my ongoing work to constrain my involvement to something manageable; and the fiddliness of shell scripts is not something I am comfortable dealing with. Please find another dev for that.

😜

**Comment by opoudjis** [comment]
````
remote: GitLab: 
remote: A default branch (e.g. master) does not yet exist for metanorma/mn-templates-nist
remote: Ask a project Owner or Maintainer to create a default branch:
remote: 
remote:   https://gitlab.com/metanorma/mn-templates-nist/project_members
remote: 
````

**Comment by opoudjis** [comment]
Posted

**Comment by opoudjis** [comment]
Structure is in place, have annotated document variables with preceding `:comment: ###`. (Bad things happen if you put anything but a `:...:` variable in the Asciidoctor header.) Will now transfer all content from the SP 800 template, including annotated instructions.

**Comment by opoudjis** [comment]
Up to p. 4 of 17
