### ISSUE TITLE
Status cover pages: "pre-final draft" stages (old)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#91]
This relates to information provided in #90 .

It has been decided that a NIST "Draft" will use these cover pages to indicate their stages (just like how ISO does it).

This cover page will replace the existing cover -- there will be no authors mentioned and no horizontal lines.

The Word cover pages are provided in `mn-nist-documents/references`.

The "warning texts" here should be implemented in some YAML form so we don't repeat in HTML/Word.

Internal draft:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/11865/55643180-1c09dd00-5805-11e9-9547-b0824447a5fa.png">

Work-in-progress draft:

<img width="615" alt="image" src="https://user-images.githubusercontent.com/11865/55643289-5ecbb500-5805-11e9-90f8-b82ba5f8c348.png">

Preliminary draft:
<img width="619" alt="image" src="https://user-images.githubusercontent.com/11865/55643322-6f7c2b00-5805-11e9-93c9-79b39086c8d9.png">

Public drafts:

* "Initial Public Draft (IPD)" is changed to "Second Public Draft (2PD)", "Third Public Draft (3PD)", ... "Final Public Draft (FPD)" as appropriate.
* The DOI link and "This publication is available at..." wording only appears when a DOI has been provided.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/11865/55643340-79059300-5805-11e9-8cc7-a5cb850b2da8.png">

**Comment by ronaldtse** [comment]
This is related to #79 and partially supersedes it.

**Comment by ronaldtse** [comment]
This issue is confirmed and ready to go.

**Comment by opoudjis** [comment]
I am hoping that for HTML, the outputs in https://github.com/metanorma/metanorma-nist-style/issues/4 will be sufficient. @ronaldtse, please confirm.

**Comment by ronaldtse** [comment]
@opoudjis can't you use Word and save as MHT, and the resulting MHT provides you with the code? That's what I did when templating.

**Comment by opoudjis** [comment]
As I've just documented:

````
* The title and introductory files may contain VML graphics, the tags for which are prefixed in Word HTML by `v:`; this applies in particular to text boxes (e.g. `<v:textbox>`). For any such prefixed tags to be recognized properly by the XML processor in Metanorma, the HTML content of the files *must* be in XHTML. Unfortunately, the Word output is anything but XHTML. To make it compliant:
** Any HTML escapes must be replaced by Unicode entities; e.g. `&nbsp;` becomes `&#xa0;`
** Any standalone tags must be closed; e.g. `<br>` becomes `<br/>`
** Any attributes must be quoted; e.g. `<p class=MsoNormal>` becomes `<p class="MsoNormal">`
````

This is a longstanding issue: Nokogiri's HTML parser, which I used to use to process title pages, does not cope with tag prefixes, and I can't get Nokogiri's XML parser to deal with Word HTML even when cleaned up. XHTML is the only solution, and it requires that cleanup. (Part of the problem was that I forgot about having to convert `&nbsp;`.)

**Comment by ronaldtse** [comment]
Warning -- the designs of "pre-final draft" cover pages will be updated.

"Pre-final Drafts":
* Internal Draft
* WIP Draft
* Preliminary Draft
* Public Draft (IPD, 2PD, 3PD, ..., FPD)

Valid states for Pre-final Drafts:
* Active
* Withdrawn (apply "Withdrawn Draft" cover)
* Retired (apply "Retired Draft" cover)

When applying a status page cover for documents at "pre-final states":
* Use the Draft Cover page first, followed immediately by the Title page

**Comment by ronaldtse** [comment]
## Valid transitions

WIP Draft:
* if ->  Prelim Draft:           apply "Withdrawn Draft" cover;
* if ->  Retired Draft:          apply "Retired Draft" cover.

Prelim Draft:
* if ->  Public Draft:            apply "Withdrawn Draft" cover;
* if ->  Retired Draft:          apply "Retired Draft" cover.

Public Draft:
* if ->  subsequent Public Draft (2PD, 3PD,…,FPD): apply "Withdrawn Draft" cover;
* if ->  Final:                        apply "Withdrawn Draft" cover;
* if ->  Retired Draft:          apply "Retired Draft" cover.

Final:
* if ->  Withdrawn:             apply "Withdrawn NIST Technical Series Publication" cover;
* if ->  Withdrawn, but with a delay (i.e., it remains active for some time):    apply "Withdrawal Pending" cover.

**Comment by opoudjis** [comment]
Can I continue work on this ticket, or are mods to the design still pending?

**Comment by ronaldtse** [comment]
Superseded by #99
