### ISSUE TITLE
Support "Review Confirm" stage in NIST pub

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#92]
According to #90 , stage 90.93 is `final(confirm)`.

This means that according to the NIST ERB 5-year review process, this standard is confirmed to be relevant and valid to date.

A document of such state will be modified to include a confirmation message on the TITLE PAGE, right under the "date" (right aligned, of course):

```
January 2019
Publication is current as of 20-09-2029
```

To put this into context it should look like the Errata message:
<img width="504" alt="PastedGraphic-3" src="https://user-images.githubusercontent.com/11865/55644017-38a71480-5807-11e9-9d75-0ff31e45869d.png">

Here "20-09-2029" is the confirmation date (the date of outcome from the review process).

This means the "confirmation date" has to be entered as a document attribute in AsciiDoc. Seems appropriate to be entered as a bibliographic date.

**Comment by opoudjis** [comment]
> This means the "confirmation date" has to be entered as a document attribute in AsciiDoc. Seems appropriate to be entered as a bibliographic date

We already support that, because it came up in GB: `:confirmed-date:`. I will mention it in the README (which has not yet migrated to metanorma.com, and given the flux, let's not yet).

**Comment by opoudjis** [comment]
> To put this into context it should look like the Errata message:

... Which you have not told me to put in, and which I WILL NOT PUT IN in this form, because I have no fricking idea what the page number of the errata is going to be in advance. Please do not ask me to do so.

**Comment by opoudjis** [comment]
In addition: the template will push through whatever date has been provided in Asciidoctor; but the grammar expects to see YYYY-MM-DD, and will mark anything else as a syntax error. I can postprocess any dates of the form YYYY-MM-DD to convert them to MM-DD-YYYY. But we have indulged NIST's contempt for standard ways of doing things too much already.

**Comment by ronaldtse** [comment]
@opoudjis for YYYY-MM-DD to MM-DD-YYYY conversion we should use the CLDR library. In fact for all the date/time stuff we should use CLDR.

**Comment by opoudjis** [comment]
>  But we have indulged NIST's contempt for standard ways of doing things too much already.

Clearly not.

**Comment by opoudjis** [comment]
I'm using CLDR for Month names. For MM-DD-YYYY, I'm using Date.strftime, since CDLR only delimits dates with slashes.

**Comment by opoudjis** [comment]
CLDR prints 2021-01-01 as "December 2020", because of https://github.com/twitter/twitter-cldr-rb/issues/215, so I have to do some bullshit workaround to force the date into UTC.

**Comment by opoudjis** [comment]
All bibliographic dates now are passed to metadata vector with variants *_monthyear and *_mmddyyyy; e.g. publisheddate_mmddyyyy.

**Comment by opoudjis** [comment]
CLDR is no strftime, and it does not natively support "December 25, 2017". I would end up having to look up the month name in CLDR, and compose the date from scratch. Which for English is meaningless. Not using CLDR for *_MMMddyyyy.
