### ISSUE TITLE
Status cover pages: "inactive" drafts/publications

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-nist#94]
There are three states that need to be considered. With all these states, the cover page is PREPENDED in the document (the published cover page REMAINS).

## 1. Retired draft -> Add retired draft cover page

<img width="616" alt="Screen Shot 2019-04-09 at 11 40 53 AM" src="https://user-images.githubusercontent.com/11865/55772860-c4979580-5ac0-11e9-8c75-3bbd364dae92.png">

* As seen above, retired draft requires input of:
  * Date (document attribute) -> bibliographic date
  * Retirement note (plain text)

## 2. Withdrawn draft -> Add withdrawn draft cover page

<img width="617" alt="Screen Shot 2019-04-09 at 12 13 00 PM" src="https://user-images.githubusercontent.com/11865/55772879-d4af7500-5ac0-11e9-9268-281d7c8f879b.png">

As seen above, a withdrawn draft requires input of the following:

* Withdrawal date (document attribute) -> bibliographic date
* Withdrawal note (plain text)
* Superseding publication URI / DOI
* Additional Information

## 3. Withdrawn publication -> Add withdrawn publication cover page

![image](https://user-images.githubusercontent.com/11865/55644537-cafbe800-5808-11e9-9884-8efe214b1872.png)

A withdrawn publication requires input of the following:

* "Archived Publication"
  * Withdrawal date (document attribute) -> bibliographic date
  * Withdrawal note (plain text)

* "Superseding Publication"
  * Superseding publication series/number
  * Superseding publication title
  * Superseding publication author(s)
  * Superseding publication date
  * Superseding publication URI / DOI

* "Additional Information"
  * Contact
  * Last revision of attached publication
  * Related information
  * Withdrawal announcement.

## 4. Withdrawal Pending publication (withdrawal is announced but with a future date) -> Add withdrawal announced message / cover page

<img width="617" alt="Screen Shot 2019-04-09 at 11 41 07 AM" src="https://user-images.githubusercontent.com/11865/55772846-b0539880-5ac0-11e9-96cf-1a6feb4c1e78.png">

As seen above, retired draft requires input of three sections (if applicable):

* Withdrawal date (document attribute) -> bibliographic date
* Withdrawal note (plain text)
* Superseding date (notice that this is earlier than Withdrawal date)
* Superseding publication series/number
* Superseding publication date
* Superseding publication URI / DOI

This supersedes #79 on the display of non-active cover pages.

This task relates to https://github.com/metanorma/metanorma-model-nist/issues/15 in how the states are realized.

**Comment by ronaldtse** [comment]
Seeking clarification.

———

A “final” publication can transition to two states:

a) “Archived / Withdrawn publication”: The PNG shows an “Archived” publication. Is “Archived” == “Withdrawn Publication”? i.e. a document can only be a/an “Archived/Withdrawn” publication after it has been “Final”.

b) “Withdrawal Pending”

For both of the above, the cover page is placed “on top” of the “final” publication cover page?

———

A draft can transition to these end states:

a) At any stage, it can become a “Retired Draft” (attached as draft-retired-cover).

b) From Public Draft, it can become a “Withdrawn Public Draft” (attached as withdrawn-public-draft-cover).

c) Can “Withdrawal Pending” be applied to a draft? Am I mixing this with b) ?

For the above, does the cover page “replace” the draft’s “draft cover page”, or placed “on top” of the “draft cover page”?  i.e. “Withdrawn/Retired cover page” -> “Draft cover page” -> Title page.

———

The “Withdrawn Pending" cover now looks different (better) than those for “Retired” and “Withdrawn”. Should they be aligned in terms of design?

**Comment by ronaldtse** [comment]
Retired draft design updated (uploaded):

<img width="513" alt="Screen Shot 2019-04-10 at 11 30 05 AM" src="https://user-images.githubusercontent.com/11865/55849644-00476380-5b84-11e9-9911-1024a471399f.png">

* Retired date: automatically generated via attribute
* "The attached draft document has been RETIRED. NIST has discontinued additional development of this document, which is provided here in its entirety for historical purposes." => Boilerplate text
* "Additional Information: See https://csrc.nist.gov for information on NIST cybersecurity publications and programs" This should be configurable, perhaps we can have a section like this?

```adoc
[warning-notice]
See https://csrc.nist.gov for information on NIST cybersecurity publications and programs
```


Withdrawal Pending design updated (uploaded):

<img width="513" alt="Screen Shot 2019-04-10 at 11 30 31 AM" src="https://user-images.githubusercontent.com/11865/55849662-0dfce900-5b84-11e9-9bd3-8dd28931af5d.png">

* "This document remains active until December 20, 2019, when it will be officially withdrawn." => Autogenerated via attribute.

* "It was superseded on December 20, 2018 by NIST Special Publication 800-37 Revision 2: https://doi.org/10.6028/NIST.SP.800-37r2. " => Autogenerated via attribute.

**Comment by ronaldtse** [comment]
## Valid states for "Inactive stages"

Valid states for Final:
* Withdrawn (apply "Withdrawn NIST Technical Series Publication" cover)
* Withdrawal Pending (apply "Withdrawal Pending" cover)

NOTE: Both states for Final are realized by a single "withdrawn" bibliographic date.

NOTE: When a "Withdrawal Pending" Final reaches the withdrawal date, replace "Withdrawal Pending" cover with "Withdrawn NIST Technical Series Publication" cover.

"Inactive stages":
* Withdrawn Draft
* Retired Draft
* Withdrawn NIST Technical Series Publication
* Withdrawal Pending Publication

When applying a status page cover for documents at "inactive stages":
* Put it on top of the existing cover (preserve the original state -- this should be an additional attribute)
  * (e.g. A Withdrawn 2PD will have: Withdrawn Draft cover, then the 2PD cover, then the title page)

**Comment by ronaldtse** [comment]
(placeholder: updated Withdrawn Draft cover page coming soon)

**Comment by opoudjis** [comment]
Is this ticket actionable yet?

**Comment by ronaldtse** [comment]
Superseded by #100 and #101 . Closing.
