### ISSUE TITLE
Implement full referencing of NIST citations

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-nist#98]
From #88 

The "full form” is used in the bibliography to refer to a NIST document.

They are currently expressed in a selection of these formats:
 
* "National Institute of Standards and Technology Federal Information Processing Standards Publication 199, Standards for Security Categorization of Federal Information and Information Systems, February 2004."
* "National Institute of Standards and Technology Special Publication 800-27, Revision A, Engineering Principles for Information Technology Security (A Baseline for Achieving Security), June 2004.”
* "National Institute of Standards and Technology Special Publication 800-39 (Second Public Draft), Managing Risk from Information Systems: An Organizational Perspective, April 2008."
* "NIST SP 800-38C, “Recommendation for Block Cipher Modes of Operation: The CCM Mode for Authentication and Confidentiality”, NIST Special Publication, May 2004.”
* "FIPS 198-1, “The Keyed-Hash Message Authentication Code (HMAC)”, Federal Information Processing Standards Publication, July 2008.”

But these are wrong. Many other pubs have elected to use the formats above, which don’t specify the author names, but Metanorma should do it right.

The NIST Library encourages usage of the following (which is adapted from the Proceedings of the National Academies of Science style):
 
* SPs and NISTIRs:
```
{author(s)} ({year}) {title}. (National Institute of Standards and Technology, Gaithersburg, MD), {Draft} NIST {series-name} ({series-abbrev}) {docnumber} {part | volume}, {revision}, {publication date} (updated {update-date}). {DOI|URL}

# {author(s)} is in the format:  LastName(s) Initial(s)
 ```

* FIPS: FIPS use a different format because the publisher is the "U.S. Department of Commerce", not NIST:
```
National Institute of Standards and Technology ({year}) {title}. (U.S. Department of Commerce, Washington, D.C.), Federal Information Processing Standards Publication (FIPS) {docnumber}, {publication date} ({change notice}, {update-date}). {DOI|URL}
```

(`docnumber` is the full FIPS number, including revision, e.g., `140-2`.)

There are also differences between citing “dated” or “undated” references.

Examples:

FIPS

* National Institute of Standards and Technology (2002) Security Requirements for Cryptographic Modules. (U.S. Department of Commerce, Washington, D.C.), Federal Information Processing Standards Publication (FIPS) 140-2, May 25, 2001 (Change Notice 2, 12/3/2002). https://doi.org/10.6028/NIST.FIPS.140-2

* National Institute of Standards and Technology (2015) Secure Hash Standard (SHS). (U.S. Department of Commerce, Washington, D.C.), Federal Information Processing Standards Publication (FIPS) 180-4, August 2015. https://doi.org/10.6028/NIST.FIPS.180-4

* National Institute of Standards and Technology (2013) Digital Signature Standard (DSS). (U.S. Department of Commerce, Washington, D.C.), Federal Information Processing Standards Publication (FIPS) 186-4, July 2013. https://doi.org/10.6028/NIST.FIPS.186-4

SP 800:

* Nieles M, Pillitteri VY, Dempsey KL (2017) An Introduction to Information Security. (National Institute of Standards and Technology, Gaithersburg, Maryland), NIST Special Publication (SP) 800-12, Rev. 1, June 2017. https://doi.org/10.6028/NIST.SP.800-12r1

* Ayers RP, Livelsberger B, Guttman B (2018) Quick Start Guide for Populating Mobile Test Devices. (National Institute of Standards and Technology, Gaithersburg, Maryland), NIST Special Publication (SP) 800-202, May 2018. https://doi.org/10.6028/NIST.SP.800-202

* O'Reilly PD, II, Rigopoulos KG, Feldman L, Witte GA (eds.) (2018) 2017 NIST/ITL Cybersecurity Program Annual Report. (National Institute of Standards and Technology, Gaithersburg, Maryland), NIST Special Publication (SP) 800-203, July 2018. https://doi.org/10.6028/NIST.SP.800-203

(full set of examples in `mn-nist-documents/references`)

**Comment by opoudjis** [comment]
Per https://github.com/metanorma/metanorma-nist/issues/95, errata releases treat the update date like in https://github.com/metanorma/metanorma-nist/issues/111, with the update date shadowing the publication date.

**Comment by opoudjis** [comment]
Ugh. Am embarking on this, using the iso690render code.

The difference in rendering between FIPS and NIST SP is not an example of "doing it right".

**Comment by ronaldtse** [comment]
Yeah, it's strange. Yet it's the format that the NIST Library requires.

Recap:

Short: "NIST SP" vs "FIPS"
Long: as above.

**Comment by opoudjis** [comment]
If NIST want "Surname, Initials", then NIST are going to have to provide "Surname, Initials" metadata for documents. Screenscraping is only going to yield complete names, and I am unwilling to parse complete names and assume that the middle of three words is a middle name and not a compound surname. If I see complete names, I am rendering complete names.

**Comment by opoudjis** [comment]
You have given rules for NISTIR, NIST SP, and FIPS. NIST is involved with 21 series, and I need to know the rules for all of them.

* Who is the publisher for each of them?
* Do they have corporate or individual authors?

Properly, this should become @andrew2net's problem in nistbib, but @andrew2net is constrained by what is available for screenscraping.

**Comment by opoudjis** [comment]
My strong preference at this point is to leave this half implemented, with just the information given here, and make NIST implement the further detail if they actually commit to taking this on. There is much too much in the way of edge cases involved here, and there is a lot of idiosyncrasy that will take weeks to elicit.

**Comment by opoudjis** [comment]
We have had three document identifiers, nist, nist-long, nist-mr. This is a fourth, because it uses both the full *and* the abbreviated series name. And the volume is not represented currently outside of the document identifier as a string; so composing the new identifier from scratch would require refactoring.

At this stage, frankly, I am not confident that the volume number won't end up concatenated to the docnumber during screenscraping, so I am declining to resolve this.

**Comment by opoudjis** [comment]
Change Notices for FIPS are not something I've seen before, yet alone modelled. I'm not handling them at this stage.

**Comment by opoudjis** [comment]
Done a basic renderer.

I must emphasise: I want you to resist the impetus to refine this rendering. Until nistbib is a lot more elaborate than it is now, I do not think it would be a good use of my time, and I think this time should be spent by NIST developers anyway, given the likely complexities and exceptions involved. The fact that I had never heard of change notices until today means that there simply is not enough work done on the bibliographical idiosyncrasies of NIST yet.

**Comment by ronaldtse** [comment]
Sorry for the delay in replying.

> You have given rules for NISTIR, NIST SP, and FIPS. NIST is involved with 21 series, and I need to know the rules for all of them.
> * Who is the publisher for each of them?
> * Do they have corporate or individual authors?

We are only handling NIST SP and FIPS right now. We don't have all the rules for the rest.

> The volume is not currently going to be extracted, because it is not currently represented in relaton (the full docidentifier was assumed to take care of that); and I do not have enough confidence in how the metadata will be provided to think it worthwhile to resolve this now. I suspect that in screenscraping, the volume number is just going to end up concatenated to the docnumber anyway.
 
I think the Volume will have to be modeled, because it is used extensively in SP 1800.

> Change Notices for FIPS are not something I've seen before, yet alone modelled. I'm not handling them at this stage.

Change notices for FIPS need to be modeled, but just like Amendments.

**Comment by opoudjis** [comment]
Volume is modelled in relaton as an extent of type volume, and I don't see a good reason not to keep that. However, I need assurance it will show up in the screenscrape and/or web service. Which of the two is needed for SP 1800, and what is an exemplar of volume being used?

**Comment by ronaldtse** [comment]
@opoudjis sorry for the late reply. SP 1800 contains volume within a document number. 

And they publish both ways: per volume, and all volumes in one. 

ie. SP 1800-123 Vol 1; SP 1800-123 Vols 1-4.

**Comment by ronaldtse** [comment]
Additional requirement for tag sorting:

In a normal string comparison:

* [SP800-116]
* [SP800-53]

In this comparison the correct behavior is:

* [SP800-53]
* [SP800-116]

So we have to parse and sort by number groups.

**Comment by opoudjis** [comment]
This ticket has stuck around too long, so I'm going to close it after the two latest stated requirements. Anything new needs to be a new ticket.

**Comment by opoudjis** [comment]
Presupposing Volumes are already encoded in relaton-nist, volumes will just be extracted as found, with the abbreviation Vol/Vols instead of `<extent type="volume">`.

**Comment by opoudjis** [comment]
Turns out I had not implemented any sorting other than numeric and alphanumeric anchors. I'll implement identifier sorting, including breaking NIST identifiers up.
